### ISSUE TITLE
Type User with fullname

### ISSUE THREAD

**Issue by Digitalin** [cosmocode/dokuwiki-plugin-struct#110]
Hi, 

I am testing Struct that works nicely (on Elenor of Tsort). I would like displaying the userlogin and the full name. In Struct Schema Editor, for two User fields, the first "fullname" is uncrossed and the second is crossed to get fullname. In both cases,  I get correct autocompletion (both userlogin and  fullname) but only userlogin is displaying in table. Did I miss someting with User Type ?

Thanks.

**Comment by splitbrain** [comment]
Currently that option only influences the autocompletion (I guess it should be a subkey of autocompletion). How the username is rendered depends on DokuWiki's ``showuseras`` configuration.
