### ISSUE TITLE
Filte placeholder $STRUCT.<column>$ is broken and under-defined

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#124]
The filter placeholder ``$STRUCT.<column>$`` as defined in the  [official doku on filters](https://www.dokuwiki.org/plugin:struct:filters#value_placeholders) does not work for a multifield as probably needs some schema information as well.

**Comment by splitbrain** [comment]
@micgro42 can you provide a (broken) test case for this? Looking at the code it should:

* work with multivalue types (using the first value only)
* accept schema info optionally. eg ``$STRUCT.schema.column$``

**Comment by micgro42** [comment]
I would expect that all values are used, not only the first. They should be OR-connected within an AND-clause

**Comment by micgro42** [comment]
Almost done, but now if $STRUCT.<column>$ is empty than that filter is treated an non-existing/evaluates always to true, however one would expect it to evaluate always to false.

**Comment by stvoigt** [comment]
Ich kehre zur�ck am 08.08.2016.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten. Herzlichen Dank
f�r ihr Verst�ndnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[cosmocode/dokuwiki-plugin-struct] Filte placeholder $STRUCT.<column>$ is
broken and under-defined (#124)" gesendet am 28.07.2016 13:54:28.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by splitbrain** [comment]
I'm unsure about the status here. @micgro42 your test is applied and seems not to fail, so I guess this has been fixed?

**Comment by micgro42** [comment]
Looks good. If something new comes up, then we can open a new issue and reference this one.
