### ISSUE TITLE
title: restoring an old revision breaks title data

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#129]
When a revision of a page using the page.usetitles=true type is restored, the content of that column gets messed up because it tries to save the raw JSON.

**Comment by micgro42** [comment]
Restoring works only when there is also a change in the text of page to be restored. Restores of struct-only changes simply do not work even so there is a success message.

Not sure that this is actually a title issue.

**Comment by splitbrain** [comment]
Hmm I think I see the problem. Not title related.

**Comment by micgro42** [comment]
Works as expected
