### ISSUE TITLE
Conflict with openlayersmap and data plugins

### ISSUE THREAD

**Issue by rnck** [cosmocode/dokuwiki-plugin-struct#139]
Hi,

I think there's a conflict with the openlayersmap plugin. No matter where I put my map on a page, the display of the single struct data is missing.

Here's a sample of a page I wanted to use with struct data:

```
<WRAP right box 580px>
<olmap id="TEST2" width="550px" height="450px" lat="52.42" lon="11.37" zoom="15" statusbar="1" controls="1" poihoverstyle="1" baselyr="OpenStreetMap" gpxfile="" kmlfile="" geojsonfile="" summary="TEST2">
52.42,11.37,0,1,marker.png,TEST2
</olmap>
</WRAP>
{{tag>tags some}}
====== A single Headline ======

Some text ...

<data foo>
number       : 1
Type         : myType
desc         : some words
</data>
```

The data tags are only there for migration. I will remove that content once I can use struct with openlayersmap.

If I remove the olmap tags, everything's fine. Is this a problem on this or the openlayersmap plugin. Please let me know if you need more information.

Cheers!

**Comment by stvoigt** [comment]
Ich kehre zur�ck am 08.08.2016.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten. Herzlichen Dank
f�r ihr Verst�ndnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[cosmocode/dokuwiki-plugin-struct] Conflict with openlayersmap and data
plugins (#139)" gesendet am 28.07.2016 14:58:05.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by splitbrain** [comment]
This seems not to be a bug related to struct. When I try the given map syntax it takes a while and then the wiki crashes with a ``Fatal error: Allowed memory size of 239075328 bytes exhausted`` error. Please report at openlayersmap plugin.
