### ISSUE TITLE
Struct data as variables

### ISSUE THREAD

**Issue by eilko** [cosmocode/dokuwiki-plugin-struct#145]
I have added several fields to a page with the use of the Struct plugin. Adding data is working great and so are the aggregated tables.

But I can't get the data of the page itself shown in the way I would like to. I have disabled the show on page feature as I don't want to see all fields and I want to combine them in a new table with some other fields. Secondly I would like to decide myself where to place the table instead of on top like the Struct plugin does now. 

**Feature request:**
Use the data of a page in the fields of the struct plugin as variables in the page. Or a way to decide where to place the Struct table on the page.

**Comment by micgro42** [comment]
You could simply make an aggregation table and filter `%pageid%` with `$ID$`. Then you have full control on what you want to show.

**Comment by eilko** [comment]
@micgro42 your suggestion makes it possible to show the table below the image instead of directly under the page name, and I can choose what to show in the table. But it is a one line table instead of a "normal" table (see example below). Besides that I would like to be able to add a row to the table that is not in the data fields as it will contain a lot of wiki (see field remarks).

<img width="732" alt="screen shot 2016-08-07 at 10 53 19" src="https://cloud.githubusercontent.com/assets/1078401/17461456/35d9a4b6-5c8d-11e6-8423-6acf68f899c3.png">

It would be great if I could make my own table like below, where the @@VARIABLES@@ are struct plugin data of that page. 

|Year:|[[:timeline:@@YEAR@@]]|
|Publication|@@PUBLICATION@@|
|Edition:|@@EDITION@@|
|Remarks:|**This** is some [[:dictionary:|random]] text //to show// the purpose|

**Comment by iainhallam** [comment]
It seems to me that this could be really powerful if you could simply specify a query to come up with a replacement for inline use rather than as a list or table:

    {{struct schemas: publication; cols: year; filter: %pageid% = $ID$;}}

To make this much easier to type, when the schema is set to, e.g., `_self`, the list of included schemas could default to whatever is assigned to the current page, and the filter could add the current page ID as a criterion automatically. In fact, if no schema is specified, this could be the default anyway, so a user would only have to do something like the following to get a single variable:

    {{struct select:year;}}

You could make a syntactic sugar version of that, too:

    {{structvar year}}

You'd still have access to any other function available to the main struct queries, though, so you could select any data value across the whole database to be used in your page.

This could also allow some calculations to be performed like:

    {{struct from: publication; select:AVERAGE(year);}}

But that would probably be a different issue to report once the basic feature was in place!

Incidentally, I don't know what syntax would have to be used - something that allows the power of the current aggregations, but can be typed inline, I guess. The above is one suggestion.

**Comment by iainhallam** [comment]
Incidentally, this would have to be evaluated before the page was passed to DouWiki's rendering engine to get the interpolation shown in @eilko's example - otherwise the links wouldn't generate correctly. That would make link building very easy and quite powerful.

**Comment by iainhallam** [comment]
One other thing to think about is whether the current user has the right to read the page on which that data is stored; I don't know enough about how struct pulls data into aggregations to know whether this would be a problem.

**Comment by iainhallam** [comment]
I have a first version of this working at https://github.com/iainhallam/dokuwiki-plugin-struct/tree/feature/value. You can start the syntax in the middle of a line, but it currently requires the multi-line syntax also used by the table aggregation. An example:

```
Here's a line with a value - ----struct value ----
schema: myschema
field: year
---- - and the text continues after the substituted value.
```

This produces the HTML:

```
Here's a line with a value - <span class="structaggregation valueaggregation"><span class="struct_decimal">2016</span></span> - and the text continues after the substituted value.
```

With no changes in CSS, that renders in the browser as, simply:

Here's a line with a value - 2016 - and the text continues after the substituted value.

I'd appreciate feedback on ideas for an inline syntax for this; I'm currently leaning towards separating the lines with `;`, but I'm not sure whether to continue with the `---- struct value` delimiter, which is quite verbose. It could look like the following:

```
---- struct value ---- schema: myschema; field: year ----
```

I'm going to add a syntactic sugar version that simply fetches a value from the first schema in the current page:

```
{{structvalue year}}
```

**Comment by fthommen** [comment]
I would clearly vote for a syntax like the following

> {{structvalue year}}

Maybe like `{{structvalue schema=myschema field=year}}` or similar.  The full blown `---- struct value ----` seems too awkward and error prone (and unreadable) for an inline syntax

**Comment by eilko** [comment]
Great to read about your progress. The {{structvalue myschema.year}} would be great. Although I have usually one scheme per page so {{structvalue year}} would work for me.

**Comment by iainhallam** [comment]
Just pushed a commit to add the shorter syntax below:

```
{{$schema.field}}
```

At the moment I haven't implemented looking up the schema if only a field is supplied. Can someone else download my branch and test whether it works for them, please?

https://github.com/iainhallam/dokuwiki-plugin-struct/tree/feature/value

If it works, then I'll submit a pull request and we can clean up anything that needs fixing before it's added to the main repo.

**Comment by eilko** [comment]
I have tested it at https://www.betaplana.be/artwork/testimage . 
It works great.

**Comment by eilko** [comment]
in another test I found a bug. 

I have added struct data to two pages, see them at https://www.altaplana.be/en/gallery/images
In the agregated view the data is correct. But when I use the new variables the data of the first page is used. 

see e.g.  https://www.altaplana.be/en/gallery/images/20-ans-de-sapristi-1

The Publication year is shown as  2004 AD, although 2002 AD is entered. Same for Printing technique where also the data of the other page is used. 

I have also added a third page and again all info is used from the first page.

**Comment by joergdd** [comment]
I've been looking for just such a feature for some time.
Hopefully this will soon be part of the plugin.

I have one hint left. If a database field is a checkbox, you should be able to define what the output should look like.

options:
Yes / No
True / False
1 / 0

**Comment by eilko** [comment]
@joergdd,  if you tick a checkbox, the struct plugin shows the label that is attached to the checkbox option. If you want to change that to two labels per checkbox option,  it should be a seperate issue as it is not part of the scope of this one.

**Comment by eilko** [comment]
@iainhallam , as I have no clue how to fix this bug I did some more testing for you and found out that the output of the  multi-line syntax also gives the value of the first entered page and not the current page. 
I hope this helps you to fix this.

**Comment by iainhallam** [comment]
Forgot to include a filter restricting results to the current page. Looking more deeply into the Struct code, it looks like schema and field names could include dots, so will have to refactor this slightly!

**Comment by iainhallam** [comment]
I've pushed a new version to https://github.com/iainhallam/dokuwiki-plugin-struct/tree/feature/value - it should now restrict `{{$schema.field}}` to the current page, and you can also do `{{$pageid.schema.field}}` to access the value from a different page. If your page ID, schema or field name has a dot in, you can enclose just that component in quotes: `{{$"pageid".schema."field"}}`.

**Comment by iainhallam** [comment]
There's still a bug, though - in my test instance, every time I save the page with any changes, I get an error about a foreach loop, but then for refreshes it goes away! Also need to put in some error checking for single quotes, because PHP's `str_getcsv` function chokes on them.

**Comment by eilko** [comment]
@iainhallam the filter work fine. And the for_each bug is gone. But now "nothing is found" is printed when a value is empty. Earlier versions just showed nothing, I prefer it that way. It just looks better in tables like this, or when you use them in a text line. Can this be "fixed"?
 
<img width="557" alt="screen shot 2018-02-26 at 18 38 53" src="https://user-images.githubusercontent.com/1078401/36685668-56d0acbc-1b24-11e8-94f8-6bdb9d193072.png">

<img width="721" alt="screen shot 2018-02-26 at 18 40 46" src="https://user-images.githubusercontent.com/1078401/36685768-9e06e65a-1b24-11e8-854e-01b75a71308d.png">

**Comment by iainhallam** [comment]
I've added it as a configuration option. If you download now, you should be able to set show_not_found to 0 in the Configuration Manager by unticking it.

**Comment by eilko** [comment]
very nice! Downloaded the update and it works fine.

**Comment by joergdd** [comment]
Would it also be possible to use a variable as a headline?
Currently this is not possible, I have just tested.

**Comment by pirminkager** [comment]
What is the status on this feature? #438 Shows a syntax but it doesnt work on my installation.

**Comment by eilko** [comment]
> What is the status on this feature? #438 Shows a syntax but it doesnt work on my installation.

the pull request has not been accepted or merged yet. This feature adds 3-4 new files, if you add those to your current version of the plugin the syntax works fine.

**Comment by eFreshman** [comment]
Unfortunately, I'm unversed with github, but I am very verry interested in this feature. Can you tell me which files are that, or how do I find that out?

**Comment by Juergen-aus-Koeln** [comment]
> I've pushed a new version to https://github.com/iainhallam/dokuwiki-plugin-struct/tree/feature/value - it should now restrict {{$schema.field}} to the current page, and you can also do {{$pageid.schema.field}} to access the value from a different page. 

Very good indeed, that helps a lot !!!

There is one thing remaining open for me:
My wish is to use this variable inside of an aggregation as filter, for example:
```
---- struct table ----
schema : fbg_ident, fbg_meta
cols   : fbg_ident.fbg-fkt, fbg_meta.fbg-mtyps
filter : fbg-schlagwort = {{$my_page.fbg_meta.fbg-mtyps}}
----
```

**Comment by alainperry** [comment]
I'm very interested in this feature and would love to give it a try, but before that I have to admit I feel kind of stupid: I can't, for the life of me, figure out how to "disable the show on page feature" as @eilko mentioned in the first post. Could anyone help me with that first step ? Thanks a lot.

**Comment by eilko** [comment]
> I'm very interested in this feature and would love to give it a try, but before that I have to admit I feel kind of stupid: I can't, for the life of me, figure out how to "disable the show on page feature" as @eilko mentioned in the first post. Could anyone help me with that first step ? Thanks a lot.

In the schema editor you can set the visibility of each field.

![Capture](https://user-images.githubusercontent.com/1078401/58167506-5ed82500-7c8c-11e9-952e-7dcb5dbbb33f.JPG)

**Comment by alainperry** [comment]
@eilko Thanks, I had not realized I could hide the whole table that way, but that makes an awful lot of sense. Thanks again and sorry for the noise.

**Comment by Juergen-aus-Koeln** [comment]
The extension is extremely helpful. When can it be expected to be available as a master release?

**Comment by bertdeb** [comment]
Bump. When can it be expected to be integrated into a master release?

**Comment by juliusverrel** [comment]
What about turning this into a separate plugin interacting with struct, rather than wait for it to be integrated in the main plugin? This would be consistent with other struct-related plugins providing extra functionality (structjoin, structgantt, etc). Most importantly, it would be easier to use it for non-git/php experts.

**Comment by fschrempf** [comment]
> The extension is extremely helpful. When can it be expected to be integrated into a master release?

The author (@iainhallam) created a PR (#386) back in 2018. There a review comments and change requests from the maintainer (@splitbrain) which were never taken care of. So if @iainhallam won't finish the work, someone else has to step up and do it.

**Comment by iainhallam** [comment]
The PR has been updated; awaiting review at the moment, and there's a question of how metadata is handled which may need a separate issue.

**Comment by annda** [comment]
It looks like we are finally approaching the finishing line with this useful feature.

@iainhallam and other interested parties, can you comment on the hopefully final questions in the PR?
https://github.com/cosmocode/dokuwiki-plugin-struct/pull/386#issuecomment-824318883

**Comment by iainhallam** [comment]
This has now been merged, and documented at https://www.dokuwiki.org/plugin:struct:aggregation. There may still be an issue with how the aggregation interacts with metadata, and the code notes that adding summarised values (`sum:` or `+`) and defaults to be used if nothing is found (`default:` or `!`) are still to do; these could be raised as separate issues.
