### ISSUE TITLE
Sorting integer fields does not work

### ISSUE THREAD

**Issue by rnck** [cosmocode/dokuwiki-plugin-struct#146]
Hi,

I have a struct field number with type integer (format %d which is default). On my aggregation page I use 

```
---- struct table ----
schema           : my_schema
cols             : lfd_nr, %pageid%, desc
dynfilters       : 1
sort             : ^lfd_nr
filter           : lfd_nr > 0
----
```

but my pages are sorted like this:

```
lfd_nr     Seite     Beschreibung          
99         Here      ...
71         are       ...
51         my        ...
149        Page      ...
148        IDs       ...
147        ...       ...
146        ...       ...
119        ...       ...
```

I think this is a bug. Or am I missing sth?

EDIT: I tried changing the field to decimals, but problem is still the same.

**Comment by micgro42** [comment]
Mh, looks like it's sorting the numbers as strings and not as numbers.

**Comment by splitbrain** [comment]
It's because all columns are TEXT internally. We need to select the Decimal values with ``CAST(col2 AS DECIMAL)``

**Comment by rnck** [comment]
I just tested the fix. It works for decimal type only. Integers are still sorted as strings. At least I can use the decimal type for my field.

Thank you, so far.

**Comment by splitbrain** [comment]
Integer fields have been removed now. The Decimal field covers all features of Integer (set ``roundto: 0``).
