### ISSUE TITLE
implement hidden mechanism

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#15]
In the data plugin we had a hidden type. It made sense as each type could later be accessed as any other type. This is no longer possible so we need a different mechanism to make every type hidden an prefill it.

I am not sure how, yet. We could put it into abstract base type's config setup similar to how the label translation is done. Or we could have a first class hidden field. But then we need another for the default value. Or we do introduce a hidden type and have it have a config to define a "parent" type.

**Comment by stvoigt** [comment]
In the most cases I used hidden just for storing the current language (%trans%) and used it for filtering. Sometimes I used hidden also for storing the date when the data set was created for sorting (newest entry first). I am telling this more for keeping in mind these usefull mechanisms. Maybe you have ideas how to solve these sorting/filtering mechanisms based on placeholders (like %trans%)... Or would it be possible to prefil these hidden type with placeholders automatically filled when a scheme is connected with a page?

**Comment by splitbrain** [comment]
Real world examples like these are extremely helpful. Thank you.

**Comment by detman** [comment]
why not add options to the field config?
- visible in view (yes/no) - should field be visible in normale page view?
- visible in edit (yes//no) - should field be visible in field editor?

having these two option you can
- prefill form fields with bureaucracy and prehibit changes lateron
- enable fields in editor, without bothering watching the normal page view

**Comment by stvoigt** [comment]
comment on @detman: yes should than be the default for both...
