### ISSUE TITLE
selecting %pageid% only doesn't work

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#150]
For some reason I don't fully understand yet it's not possible to select only `%pageid%`. The search query returns an empty result set. As soon as you add another column it works.

**Comment by micgro42** [comment]
The reason is #114 . If all rows except `%pageid%` are null then we consider that schema empty for that page. Also `%lastupdated%` is also not handled.

**Comment by fschrempf** [comment]
Seems like this was fixed long ago. Would someone mind closing this issue?
