### ISSUE TITLE
incompatible with php < 5.5

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#168]
The newest version uses the `finally` clause, which is only available in php 5.5 and newer. This causes fatal errors on servers with php 5.3 and php 5.4.

See commits 13eddb0f545f8f41b29b77f59e797a50081d9821 and 60fc908182b62ebb99d8e848d84a26418d363e63

**Comment by splitbrain** [comment]
Yeah, I listed the minimum requirements at 5.6: https://www.dokuwiki.org/plugin:struct#installation
