### ISSUE TITLE
Schema self-reference

### ISSUE THREAD

**Issue by Xeenych** [cosmocode/dokuwiki-plugin-struct#171]
I add a new schema named "region" and create two fields:
"name" is of type text
"child" is of type dropbox with schem region and fiedl name

After svaing this schema it is no longer accesible. Also it breaks pages assigned to this schema.

**Comment by splitbrain** [comment]
Hmm currently the Dropdown type is meant to be used with lookup schemas. But it might make sense to allow the use of page schemas too. self referencing might create other problems as well. gotta check that.
