### ISSUE TITLE
last release issue

### ISSUE THREAD

**Issue by Digitalin** [cosmocode/dokuwiki-plugin-struct#174]
Hello, 

the last release (2016-08-25) seems to have an issue.  With Bootsrap3  template, it blocks the Admin drop down bar, the ?do=admin doesn't work. However, the ?do=admin&page=config|extension still works (more css stuff in extension page).
I check on a fresh install with DokuWiki default template and it freezes completely or has same behaviours than those described above.

Edit :  as it is said on [DokuWiki Struct page](https://www.dokuwiki.org/plugin:struct#installation) : 

> Please also note that this plugin requires PHP 5.6 or higher. 

I have installed 5.6 and still have the issue ([see forum](https://forum.dokuwiki.org/thread/14055))

**Comment by Digitalin** [comment]
I get in  apache error log  : 

`[client 127.0.0.1:50994] PHP Fatal error:  Call to a member function getAdapter() on null in /~/www/dokuwiki/lib/plugins/struct/helper/db.php on line 64
`

**Comment by micgro42** [comment]
Please check that your sqlite-plugin updated to the current version and that your php supports sqlite 3.

**Comment by Digitalin** [comment]
on line 65 struct/lang/fr/lang.php 
`$lang['Exception schema missing'] = 'Le schéma %s n\\'existe pas !';`

`n\'existe pas`

all works fine on PHP Version 5.6.25-2+deb.sury.org~trusty+1 and PHP Version 5.5.9-1ubuntu4.19 as well  :smile:
works also with PHP Version 7.0.10-2+deb.sury.org~trusty+1 but with a bunch of errors : 
`PHP Warning:  Declaration of syntax_plugin_(cellbg|doodle|todo|schedule)::(handle|render)`

update and install from plugin page doesn't work. Have to install from download.

**Comment by Laynee** [comment]
I've submited a pull request to fix this error in struct/lang/fr/lang.php.

**Comment by Laynee** [comment]
See #186
