### ISSUE TITLE
How to track who edited entries in lookup tables?

### ISSUE THREAD

**Issue by bobdeh** [cosmocode/dokuwiki-plugin-struct#178]
Hello,

how can i track who made changes to any entries? My use case is a closed Wiki with about 2000 registered users. If someone writes "crap", where can i check who wrote it?

Thanks in advance, Bob

**Comment by micgro42** [comment]
Changes to struct data should be tracked in the revisions history of a page.

**Comment by bobdeh** [comment]
Thanks for the reply, but i would like to use lookup schemas and not page schemas. Sorry it forgot to mention this.

**Comment by micgro42** [comment]
This is not possible, because there is no history for lookup schemas. However it is planned to add a permission-system to struct so you can limit the edit-rights for your schemas to trustworthy users. I hope to get this feature done early to mid October, but no guarantees.

**Comment by bobdeh** [comment]
Okay, in that case i will have to evaluate if i go with restricted access or if i go with page schemas. By using a special namespace i could avoid mixing normal pages with pages just created for schemas.
Nevertheless, something like a reserved optional "last_edit_by" row could be a useful feature for lookup tables.
