### ISSUE TITLE
Better Styling for Entry Editor

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#18]
The Entry-Editor should be styled a bit nicer. We also have to decide if it should be collapsible. If so is it collapsed by default? Is the collapsed state saved in a cookie?

**Comment by splitbrain** [comment]
Styling is okay now. The question on collapse is still open.

**Comment by detman** [comment]
when more than one schema is used, collapsing is necessary. each schema should be collapsable on its own. collapsing state should be preserved for each schema. default state should be open.

**Comment by micgro42** [comment]
I agree with @detman. Using a cookie to store the collapse state implies its transmission to the server, right? I don't see the use for this. [sessionStorage](https://developer.mozilla.org/en/docs/Web/API/Window/sessionStorage) should be enough for this purpose. Or am I missing something?

**Comment by splitbrain** [comment]
cookies can be set via Javascript. we already have a preference cookie that stores stuff like this. see lib/scripts/cookie.js

**Comment by splitbrain** [comment]
toggling implemented in 5d5ff98
