### ISSUE TITLE
Inline Edit with Bootstrap3 Template opens two popups

### ISSUE THREAD

**Issue by bobdeh** [cosmocode/dokuwiki-plugin-struct#182]
When using Bootstrap3 Template and double clicking entry in table to open inline edit, additional to the correctly displayed popup a second popup appears in the upper left corner. This popup cannot be closed.
The page has to be reloaded to fix this.

**Comment by bytecrook** [comment]
This also happens in vector template.

**Comment by micgro42** [comment]
Not sure if this is actually a Bug with the plugin or with the template, but I may look into it when I find the time. Though you may want to open Bugs with those templates as well.
