### ISSUE TITLE
Assigning schema adds an additional do=search

### ISSUE THREAD

**Issue by bytecrook** [cosmocode/dokuwiki-plugin-struct#183]
When I try to add a page/namespace to the schema, clicking the 'Add' button appends "do=search&id=" (see example below). The main page is then displayed, and the new page is not added. Deleting these characters will add the page/namespace correctly. 

Example URL after clicking 'Add':
localhost/doku.php?do=admin&page=struct_assignments&sectok=ff5eafa50ead91e91be14ebc8bec8717&assignment%5Bassign%5D=test&assignment%5Btbl%5D=projects&action=add**&do=search&id=**

**Comment by micgro42** [comment]
oO
What Browser and DokuWiki-Version are you using?

**Comment by bytecrook** [comment]
Chrome (Windows 10) Version 53.0.2785.116 m (64-bit)
Dokuwiki Release 2016-06-26a "Elenor of Tsort"

**Comment by splitbrain** [comment]
I can not reproduce this

**Comment by bytecrook** [comment]
Sorry for the trouble. I don't know what the problem is - maybe it's just my configuration. Also, not sure if this makes a difference but I am using the vector template. I've tried just creating a form with a text and submit button, but that posts the action correctly. I'll see if I figure it out.

**Comment by splitbrain** [comment]
Any news here? Can I close this?

**Comment by bytecrook** [comment]
Sorry I haven't had time to spend on this. I'd say just close this. If I get any new information, I'll post it here.
