### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by Czocher** [cosmocode/dokuwiki-plugin-struct#184]
Hello,
There's an issue with the pagination - it doesn't work due to an error [here](https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/meta/SearchConfig.php#L73).
It shouldn't be `setLimit` but `setOffset`. I can make a pull request if you'd like.

**Comment by micgro42** [comment]
Thank you for catching this  bug :)
