### ISSUE TITLE
Compatible with file syncing?

### ISSUE THREAD

**Issue by mlinchitstest** [cosmocode/dokuwiki-plugin-struct#189]
`Question`

If I use dropbox to sync dokuwiki text files (but not database files obviously) across computers, can I still use this addon? I know most programs that use databases cannot be synced without loss of data, but maybe strata just gets all the data it needs from the text files alone (and then maybe caches them in a database).

Say you take dokuwiki file with some strata records to another computer and edit it in a plain text editor. You then sync the file back to the computer where strata is installed. Does strata know I changed anything?

PS: I'm really new to this plugin so sorry if this sounds stupid, but what about schemas? If schemas are just taken from text files (as in you update a text file and the plugin updates the sqlite schema), then it should also be possible to "sync" schemas, no?

Thanks

**Comment by mlinchitstest** [comment]
As far as I can tell, the answer is no however there are ways to sync two sqlite database, and it should be pretty easy considering that in a personal wiki only one will be used. Though maybe there are ways aside from database syncing to get perfectly identical wikis on multiple machines (or one local one hosted)

**Comment by micgro42** [comment]
SQLite, unlike other databases, works from files alone (though not text-files). If you sync the entire data/ and conf/ directory of your wiki you should be fine and _struct_ should work as expected.
