### ISSUE TITLE
Integrate with Bureaucracy Plugin

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#19]
It will be desirable to create pages with attached data from the Bureaucracy plugin. We have to find a way to do that. It will also be desirable to reuse the valueEditors inside a Bureaucracy form.

We need ideas on how to do that. What would be desirable syntax for bureaucracy?

**Comment by stvoigt** [comment]
As we are making the schemes dynamically changeable, it would be great just name the used scheme in bureaucracy so you do not have to change the form when changing the scheme. Thus the form should always provide the same input stuff as the editor used when editing a page connected with a scheme. 
Syntax: use_stuct_scheme: scheme-name
Would be great to make "scheme-name" a variable to handover via the URL as other bureaucracy inputs right now. That would make forms reauseable for different, similar stuff.
I think, we would need these "comment" things we used in data-plugin to describe the values within a scheme. This should then be displayed within the bureaucracy too. 

What still seems tricky, is the handover to the template or better said, making the template changeable... I have no idea how to make this more useable and maintainable...

**Comment by splitbrain** [comment]
I think that wouldn't be flexible enough. Currently we often prefill data entries from a bureaucracy generated page without asking the user. Your suggestion would require the user to fill out every struct field themselves. 

Also you may want to use user input in struct data and in the page via template variables. So there needs to be a way to use input in placeholders and struct.

**Comment by stvoigt** [comment]
Where do you prefill the data entries within the wizard already or when applying the vaules to the template? In the fist case the values could be prefilled in the valueEditors. In the second case we could exclude certain struct-entries from form, e.g.: use_stuct_scheme: scheme-name ! abc, xyz. Would this be useful? 

The second part of your comment would mean from my point of view to make struct-data useable in templates again. But as mentioned above, I have no how to make that flexible. If you use the names from the schema as names for the input-types in bureaucracy (automatically), they would be useable in the templates to, would'nt it? (But that is not that flexible when changing struct scheme)

**Comment by splitbrain** [comment]
Single fields now work but there's still thing to do on them before moving on to full schemas:

- [ ] support error class for highlighting validation errors
- [ ] support asterisk for mandatory fields
- [ ] adjust styling to have bureaucracy and struct fields have matching sizes

**Comment by splitbrain** [comment]
This is now implemented but not (unit) tested, yet. Since the bureaucracy plugin is quite complex and only has few tests, there might be a whole bunch of side effects I did not think of.

Bureaucracy and struct has been updated on the wizmo and ifak wikis and is ready to be (manually) tested. See https://www.dokuwiki.org/plugin:struct:bureaucracy for documentation. @detman @stvoigt please check it out and see if it satisfies your requirements.

**Comment by stvoigt** [comment]
Styling could be more consistent. See in Foo: ifak:templates:forms:new_project or ifak:templates:forms:new_meeting as examples.

**Comment by stvoigt** [comment]
Support asterisk for mandatory fields does not work. Even if a struct_schema is optional, the asterisk is shown (but the fields keep optional). See Foo: ifak:templates:forms:new_test.

**Comment by stvoigt** [comment]
Handover of data to the bureaucracy form does not work yet or at least I do not know the right syntax. (maybe not implemented yet => new ticket needed?)

I have tried 
"new_project?@target_system@=Test" (See FOO: ifak:projects:start&rev=1459778633) 
"new_project?@ifakprojects.target_system@=Test" (See Foo: ifak:projects:start&rev=1459778593)
but non of them worked.

**Comment by splitbrain** [comment]
I don't understand your comment about the styling. Can you explain what is inconsistent? Maybe add an annotated screenshot?

**Comment by splitbrain** [comment]
The bureaucracy plugin expects the URL placeholders to have underscores instead of spaces and dots for some reason (I am sure it made perfect sense and some point in the past :suspect:). So ``ifakproject.target_system`` becomes ``ifakproject_target_system``. I adjusted foo>ifak:projects:start accordingly.

**Comment by stvoigt** [comment]
what I have meant with better styling:
- alignment of labels differes between normal fields and stuct fields
- textboxes have different widths (approx. double) => I guess, that the empty space at sturct textboxes is resvered for hints, but than the bureaucracy textboxes should have the same empty space too
- dropdown-boxes are wider than normal struct text boxes (I guess thats because of the drop down triangle)
- date boxes (bureaucracy) are aligned left, but all other are aligned ight

![struct_bureaucracy](https://cloud.githubusercontent.com/assets/2620833/14280132/333018d4-fb31-11e5-8e31-83d4e739545e.png)

**Comment by splitbrain** [comment]
You might need to clear your browser cache. It looks much different for me.

**Comment by stvoigt** [comment]
Absolutely, that helped a lot :)

**Comment by splitbrain** [comment]
@stvoigt can you confirm that this now works as expected?

**Comment by stvoigt** [comment]
Yes I can :)

**Comment by splitbrain** [comment]
perfect :-)
