### ISSUE TITLE
bureaucracy support: Creation of pages with specific field value don't work

### ISSUE THREAD

**Issue by stefanobasta** [cosmocode/dokuwiki-plugin-struct#191]
The syntax:
Action template templates:product @@product.name@@
creates a page with the ID of all entered field values from schema 'product' separated by _.
For example product.name=file1, product.date=2016-11-11, product.number=11 creates the ID:
'file1_2016-11-11_11' instead of 'file1'

**Comment by micgro42** [comment]
Do you happen to have an `@` next to the line defining the schema, similar to
```
  struct_schema  product @
```
?
Don't do that. If you remove that `@` and then have a Form that looks like
```
<form>
Action template templates:product @@product.name@@
  struct_schema  product
  submit "Create new product"
</form>
```
it should work as intended.
