### ISSUE TITLE
Hyphen in Schema Name

### ISSUE THREAD

**Issue by ewa-ny** [cosmocode/dokuwiki-plugin-struct#199]
When I use 

```
---- struct table ----
schema: student-data
cols: first-name,last-name, street, city, state, zip
----
```

I cannot sort my columns by clicking on the headers.

When I use

```
---- struct table ----
schema: student-data
cols: %pageid%,first-name,last-name, street, city, state, zip
----
```

I get the error 

```
Table Alias does not exist [QueryBuilder.php:45]
```

This did not happen when my schema name does not contain a hyphen. Can someone confirm the hyphen is the problem?

**Comment by splitbrain** [comment]
Hyphens are not allowed in schema names. If you look careful you will see that your schema is named ``studentdata`` not ``student-data``.

**Comment by ewa-ny** [comment]
As a casual user, it certainly _looks_ like my schema name was allowed to contain a hyphen (based on what pops up in the schema editor window). I appreciate you confirming that this was indeed the error.
![schema-name](https://cloud.githubusercontent.com/assets/23244869/20067530/8a117498-a4e3-11e6-877f-ad24ddffb95a.jpg)

**Comment by splitbrain** [comment]
That's weird. I cannot reproduce this. When I try to create a new schema with a hyphen it gets automatically cleaned up.

**Comment by ewa-ny** [comment]
Yes, I see now that the name is cleaned up in the list on the right-hand side of the Schema Editor. (Both "anotherschema" and "studentdata" were created with hyphens.) I was using what was showing in the drop-down menu when editing a schema. The hyphens persists in the drop-down menu for me. Adding a note about the name restriction on the [Schema Editing](https://www.dokuwiki.org/plugin:struct:schemaedit) page may help others avoid this error. That was where I looked for guidance.

Just for the record, I love dokuwiki and was just experimenting with struct for a future project. Keep up the good work!

![screen-shot2](https://cloud.githubusercontent.com/assets/23244869/20076876/10f6432a-a508-11e6-9e97-df092df2da6d.png)

**Comment by splitbrain** [comment]
that's not a dropdown. It's your browser's autocompletion for previously filled in values.

**Comment by ewa-ny** [comment]
Oops, sorry about that.
