### ISSUE TITLE
Better Styling for data display

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#20]
Currently we display a standard table at the end of the page. This definitely needs better styling.

**Comment by stvoigt** [comment]
As the current dokuwiki standard template has a lot of empty space, I could imagine, that the right sidebar would be a good place for that. Fixed (not moving when scrolling) right below the sidebar toolbox. IMHO I think a simple table with variable name/label and value should be okay. 
Even better, if it could be selected within the admin tools were to display. If we could alter the style via css in the admin template design section this would be great...

**Comment by splitbrain** [comment]
The sidebar is out of question - that's too template specific. Also the dokuwiki template only has a left sidebar ;-)

**Comment by splitbrain** [comment]
For now I styled the output as another section in the page (see comments in 5a1eab7)

**Comment by splitbrain** [comment]
- [ ] don't display empty data
- [ ] add schema headlines

**Comment by stvoigt** [comment]
Regarding schema-headlines: it would be great to have this translation stuff also for the schema-name itself. Not all schema names are that much self-explaining ;)

**Comment by splitbrain** [comment]
added #45 for that.
