### ISSUE TITLE
Sorting Dropdowns from Lookup Tables

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#203]
I am not sure, how the sorting of values is done in a dropdown field based on a lookup table. I supposed that it would be in the same order as in the lookup table. Therefore I added a number within my workflow lookup table (see screenshot). The ordering I got was maybe an alphabetical one, first with upper case followed by alphabetical order in lower case. I think, it should be case insensitive in alphabetical order. 
Maybe it would be an enhancement to make it configurable: alpahbetical or numbered order or order by a certain column of the lookup table? Also reverse order could be useful.
![zwischenablage01](https://cloud.githubusercontent.com/assets/2620833/20140038/44810acc-a689-11e6-8767-54e398046802.jpg)
![zwischenablage02](https://cloud.githubusercontent.com/assets/2620833/20140043/4bcc9a4e-a689-11e6-80c6-15e5d736a621.jpg)

**Comment by splitbrain** [comment]
Ordering them alphabetically would be relatively simple. Ordering them by a different field would be more complex.

this might be slightly related to #188

**Comment by splitbrain** [comment]
Actually those values are sorted already. However sqlite does a case sensitive sort by default. I look into doing it case insensitive instead.
