### ISSUE TITLE
Users are not linked in lookup tables

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#209]
When you have a user data type in a lookup table (existingonly is checked), the user is not linked to the user profile. In "nomal" struct tables they are. Bug oder enhancement?

**Comment by splitbrain** [comment]
Hmm I can not reproduce this

**Comment by stvoigt** [comment]
Do I have to config something before? 
![zwischenablage01](https://cloud.githubusercontent.com/assets/2620833/20262507/cbe9880e-aa62-11e6-97aa-01541893e667.jpg)

**Comment by splitbrain** [comment]
What's the config for your user field? I really don't see a reason why this should work for normal aggregations but not for lookups. It's basically the same code.

**Comment by stvoigt** [comment]
I did not test a normal aggregation yet (just mentioned it, because I know we have this functionality). I just installed struct in our internal ICKEwiki and started with a lookup table. I will test this tomorrow, when I am back at office...

**Comment by stvoigt** [comment]
Maybe this is also linked with the ICKE-template (I have tested this in our internal wiki)? I have tested a page struct with user field. The users entered here are not linked too. (In the entry and in the aggregation.) I had deactivated and activated "usercontact plugin", both with same results. Can you reproduce the bug at ICKEdemo?
![zwischenablage01](https://cloud.githubusercontent.com/assets/2620833/20297531/4411473c-ab11-11e6-886b-8d1ac52df388.jpg)

**Comment by stvoigt** [comment]
my config of the user field in the lookup table:
![zwischenablage01](https://cloud.githubusercontent.com/assets/2620833/20297651/d980043e-ab11-11e6-84a6-cbfaeeeacd2a.jpg)

**Comment by stvoigt** [comment]
I tried to deactive plugins that deal somehow with user-profile-links (do-plugin, log-plugin, usercreatepage-plugin). But this did not help. There is a config for the ICKE-template where to link user-profiles to. Maybe this helps?

**Comment by micgro42** [comment]
works for me in ickewiki and with the same configuration. What is your config value for `showuseras`?

**Comment by stvoigt** [comment]
full name of the user...

**Comment by micgro42** [comment]
try the one that includes "as interwiki link" ;)

**Comment by stvoigt** [comment]
this helps! but now they link to user/username. where can I change this? my profiles are "user/username/start". (it is the same way as in the ICKEdemo)
Sorry for making confusion here ;) Should we mention this in the struct-plugin-documentation for such smart users like me?

**Comment by splitbrain** [comment]
This is already mentioned in the documentation: https://www.dokuwiki.org/plugin:struct:type_user

**Comment by stvoigt** [comment]
how embarrassing... sorry!
