### ISSUE TITLE
schema saving is slow

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#216]
Saving a schema seems too slow. When I was debugging I noticed that some code was executed that I didn't expect - I didn't investigate because I was doing something else, but we should check what's going on during the schema save and see if we can improve it.

**Comment by splitbrain** [comment]
Observation: saving a schema updates the ``tseed`` cachebuster on the CSS and JS links - that requires them to be reloaded. The tseed is calculated in ``tpl_metaheaders()`` like this:

```
    $tseed   = $updateVersion;
    $depends = getConfigFiles('main');
    $depends[] = DOKU_CONF."tpl/".$conf['template']."/style.ini";
    foreach($depends as $f) $tseed .= @filemtime($f);
    $tseed   = md5($tseed);
```

So it looks like saving a schema updates one of the config files' lastmod dates.

**Comment by splitbrain** [comment]
Okay this was introduced by c327364 by @micgro42

**Comment by micgro42** [comment]
So, what is taking a long time is then not actually saving the schema, but the initial pageload afterwards?

**Comment by splitbrain** [comment]
Yeah that seems to be the case. I don't know what I saw on that previous debugging session but I couldn't find any illegitimate execution path anymore.
