### ISSUE TITLE
pagination has wrong colspan

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#217]
I currently have this:

![download](https://cloud.githubusercontent.com/assets/86426/20389031/dc698686-acc7-11e6-87a2-480c97f8cb5c.png)

Using this code:

```
---- struct table ----
schema: pageschema
dynfilters: 1
rownumbers: 1
limit: 3
cols: %title%, %lastupdate%, *
----
```

My schema looks like this:

![download 1](https://cloud.githubusercontent.com/assets/86426/20389119/56c53402-acc8-11e6-80eb-5322dbc69a29.png)

Export here: https://commie.io/#aUAcDYMy

The whole problem might be related to the disabled columns.

**Comment by micgro42** [comment]
What exactly is the expected behavior?

**Comment by micgro42** [comment]
Turns out it's the `*`. The colspan is calculated with the number of rows in the definition (e.g. `%title%, %lastupdate%, *`) instead of the number of rows actually visible.
