### ISSUE TITLE
Error message "Saving with zero timestamp does not work."

### ISSUE THREAD

**Issue by asdfsteve** [cosmocode/dokuwiki-plugin-struct#235]
I created a page schema and assigned it to a page. When trying to add a row I get the following unhelpful error message:
<img width="966" alt="screen shot 2016-11-29 at 11 15 31" src="https://cloud.githubusercontent.com/assets/10453305/20705925/3c133f76-b625-11e6-8efd-62afe09823c0.png">
The error message can be found in the code [here](https://github.com/cosmocode/dokuwiki-plugin-struct/blob/38ad376d2eaad62ebdfea19d248f0de7c2e5f7ac/meta/AccessTableData.php#L63), but I'm unsure how the saveData function is called or why the timestamp is 0

These are my schema and page assignments:
<img width="944" alt="screen shot 2016-11-29 at 11 18 03" src="https://cloud.githubusercontent.com/assets/10453305/20706018/8ea35fa0-b625-11e6-93fd-718b15f4be64.png">
<img width="471" alt="screen shot 2016-11-29 at 11 18 16" src="https://cloud.githubusercontent.com/assets/10453305/20706019/8ea3a1ae-b625-11e6-98cf-6eb40ca1e71a.png">

**Comment by splitbrain** [comment]
Your screenshot shows the lookup editor. You can't edit a pageschema with a ``---- struct lookup ----``.

I'm not sure why the editor even loads for you. You should have gotten an error way earlier. Gotta look into it.

**Comment by exemplari** [comment]
I am getting this error using bureaucracy and lookup schema select field. Removing the lookup schema field and it works.
