### ISSUE TITLE
Feature wish: CSV  import

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#239]
Since the struct plugin can export CSV files, why not also implement a CSV import?  That would come in handy to replace spreadsheet-based data.  W/o import capability, users will continue to keep legacy data in spreadsheets outside the Wiki.

f.

**Comment by Laynee** [comment]
What a great idea, it would be super handy ! I've got lots of Excel files that I'd love to display / manipulate / filter within the wiki. But entering all the data manually is too time consuming so I never tried. Importing all these data with a click on a button would be awesome.
And when I think about all the people who list things in spreadsheets, and all the software / scripts / apps that can export csv files... well, this feature could be insanely popular !

**Comment by splitbrain** [comment]
This has been implemented.
