### ISSUE TITLE
Add many decimal fields in one field

### ISSUE THREAD

**Issue by Digitalin** [cosmocode/dokuwiki-plugin-struct#251]
I would like to add some decimal fields in one. For instance : 
service A - service B - service C with total for each and
total service as addition of A B C 
How to get that ?
Is there other algebraic operations possible than addition ? 
Just a detail, when I put the option summerize:1 in a page schema, I get well the result but with this sign ∑  before  the number.

**Comment by splitbrain** [comment]
I'm not sure I understand what you're asking for. There are no algebraic operations in struct except for the summarize option for aggregations.
