### ISSUE TITLE
Table aggregation - "Align" not working

### ISSUE THREAD

**Issue by helimech** [cosmocode/dokuwiki-plugin-struct#258]
Tried on two separate Dokuwiki installs (though the installs are very similar) but I cannot get the "align" columns option to work when using a table aggregation. Using Ubuntu server 16.04 and PHP 7 with all updates and latest Dokuwiki. I am also using Bootstrap3 template, as well as edittables and datatables plugins but I tried disabling all of those to no avail. All other features seem to work fine.

Syntax I am using (although I have also tried things like single,double quotes, brackets, and the full words for the alignments)

\---- struct table ----
schema: workorder
cols: %pageid%, customer, product, serialnumber, workscope, duedate, estdate, status
align: l,l,l,c,c,c,c,c
filter: %pageid%~*wip:cshop*
filter: closed=no
head: WO\#
csv: 0
\----

**Comment by splitbrain** [comment]
This is actually a bug in the documentation. That feature hasn't been implemented. But it shouldn't be too hard to add.
