### ISSUE TITLE
installation kills wiki - syntax error, unexpected 'finally' ...line 156

### ISSUE THREAD

**Issue by aubreyz** [cosmocode/dokuwiki-plugin-struct#260]
Installation kills my setup completely. Every page is replaced by error line:

Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in X:\Dropbox\DokuWikiStick\dokuwiki\lib\plugins\struct\action\inline.php on line 156

No actual use of plugin in code - this is immediately post install
This is a standard stick installation with several other plugins which I can list if that proves relevant.
Resolved by manual deletion of plugin folder.

**Comment by splitbrain** [comment]
Running an old PHP version? This plugin needs 5.6 at least.

**Comment by aubreyz** [comment]
Update: I trued to uninstall the sqlite plugin and then reinstall both sqlite and struct - same outcome. 

I then started an entirely new and clean stick install from the website (version downloaded 13/1/17) and added ONLY the sqlite and struct plugins, with the same crash after installing struct


Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in C:\Users\Aubrey\Downloads\dokuwiki-with server as downloaded\DokuWikiStick\dokuwiki\lib\plugins\struct\action\inline.php on line 156

I wonder whether there is some reason struct doesn't work on the stick version?

**Comment by aubreyz** [comment]
OK. Php is whatever is on the stick version (or at least as of last week) - how do I determine php version in your stick download?

**Comment by aubreyz** [comment]
No PHP version is fine

**Comment by aubreyz** [comment]
Many thanks Andreas.  This is probably a stupid question, but how do I actually get the update? The version I can see on Github (and the version that is uploaded via the plugin manager) is still the November version which brings the wiki down.

**Comment by aubreyz** [comment]
I tried to simply replace inline.php with the new version, but this just gives a different error now

Parse error: syntax error, unexpected '{' in C:\Users\Aubrey\Downloads\dokuwiki-with server as downloaded\DokuWikiStick\dokuwiki\lib\plugins\struct\action\inline.php on line 160

(This is as before on a fresh stick install with only additions struct, sqlite and the modified inline.php

**Comment by splitbrain** [comment]
Actually the problem is indeed the PHP version. For some reason the stick version is not including the proper version. I'll look into it.

**Comment by splitbrain** [comment]
Please try a new download of the DokuWiki stick version. It should now contain the proper PHP release.

**Comment by aubreyz** [comment]
I feel really bad.....
The new stick version at https://download.dokuwiki.org/ (which still says php 5.6.3 on the webpage)
doesn't connect to localhost:8800/doku.php.. at all. (not a struct issue - not at the stage of installing that..)
Sorry....
Tried on Firefox and edge

**Comment by splitbrain** [comment]
Hmm I can confirm something is wrong n Windows 10. I had tried the new build on Windows 7 only and it worked fine there. I have to investigate what is going wrong there, but it might take a few days. Not your fault at all... stay tuned.

**Comment by splitbrain** [comment]
@aubreyz could you try a new download of the stick version again. I think it should now run correctly but I'm not a regular windows user so your help with testing is greatly appreciated.

**Comment by aubreyz** [comment]
a) I can confirm that it installs and runs on Windows 10
b) I successfully installed sqlite and struct plugins - without any errors now. Not tested beyond that. 
You need to change what it says on Download page https://download.dokuwiki.org/ about PHP version on stick (it says 5.6.3).
Am extremely appreciative of all your efforts for me and the world.
