### ISSUE TITLE
New Feature: Hierarchical lists as aggregation type

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#261]
It would be great if struct data could be aggregated as a hierarchical list I.e. instead of

- header1 col1 header2 col2 header3 col3
- ...

we'd have

- header1 col1
  - header2 col2
  - header3 col3
- ...

This kind of list is often better suited for displaying data on pages. Various customizations (type of list, content of first element etc. etc.) are thinkable.

 [Issue #145 (Struct Data as Variables)](https://github.com/cosmocode/dokuwiki-plugin-struct/issues/145) would offer an even better flexibility but probably a the cost of higher complexity of implementation.

frank

**Comment by iainhallam** [comment]
If you just want a single list on a page, you can now use the syntax `{{$schema.col}}` using the [value aggregation](https://www.dokuwiki.org/plugin:struct:aggregation#value).

**Comment by fthommen** [comment]
Unfortunately a single list doesn't suffice for my use case

**Comment by annda** [comment]
Nested lists have been implemented in #644
