### ISSUE TITLE
Summarize in lookup is not working

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#262]
I am using a lookup-table in an ICKEwiki:

`---- struct lookup ----`
`schema: promotioneinladung`
`dynfilters: 1`
`summarize: 1`
`----`
The table works fine, but I do not get a sum row nor an error message.

**Comment by splitbrain** [comment]
summarize and rownumbers are disabled for lookups because it would be hard to update those with the lookup editor. Would you think it to be okay to enable summarize but have it only work after a page reload when you edit data?

**Comment by stvoigt** [comment]
This would be absolutely okay for me...
I could not see from documentation, that summarize / row numbers is disabled for lookup. Maybe we should give another column "works with lookup" here: https://www.dokuwiki.org/plugin:struct:aggregation or just list them simply here: https://www.dokuwiki.org/plugin:struct:lookupedit

**Comment by splitbrain** [comment]
It's a wiki ;-) feel free to update the docs where needed.

**Comment by stvoigt** [comment]
Done...

**Comment by stvoigt** [comment]
Works fine. Thanks. So it is only row numbers from aggregation syntax that is disabled in lookup? => I want to update the docu...

**Comment by splitbrain** [comment]
correct. only row numbers are disabled.
