### ISSUE TITLE
Update Lookup Schemas 

### ISSUE THREAD

**Issue by pathologicalhandwaving** [cosmocode/dokuwiki-plugin-struct#270]
The latest update to Dokuwiki made all my lookup schemas freeze (unable to add more entries to tables)

I have checked my ACLs and admin status is still present but nothing seems configurable that makes these schema operable again

Using advanced config plugin nothing is different except the upgrade

Any suggestions?

**Comment by splitbrain** [comment]
Do you get any errors in the JavaScript console? Is the entry form shown?
