### ISSUE TITLE
How to configure Type Page?

### ISSUE THREAD

**Issue by ethenguo** [cosmocode/dokuwiki-plugin-struct#272]
Hello,

I am using this plugin, the Type Page. But I don't understand "[autocomplete.namespace](https://www.dokuwiki.org/plugin:struct:type_page#configuration)" configuration.

My Page Schema settings:
```
            "colref": 6,
            "ismulti": true,
            "isenabled": true,
            "sort": 5,
            "label": "test_field",
            "class": "Page",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "usetitles": false,
                "autocomplete": {
                    "mininput": 1,
                    "maxresult": 10,
                    "namespace": "playground",
                    "postfix": ""
                },
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
```

If test_field value=aaa, bbb, ccc
what should be the link URL on wiki page?

My result was below, no namespace "playground"
```
http://localhost/dokuwiki/doku.php?id=aaa
http://localhost/dokuwiki/doku.php?id=bbb
http://localhost/dokuwiki/doku.php?id=ccc
```

Thank you very much!

**Comment by splitbrain** [comment]
This only configures the autocomplete. It will search the given string in the namespace, if a page is found it is suggested to be used. If you enter something that doesn't exist it will be simply used as a link as is.
