### ISSUE TITLE
handle deassignment

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#28]
When a page had a schema assigned previously and then the assignment is removed, this page should no longer have any of the schema data associated. Otherwise the page would still be found in aggregations.

The question is how to achieve this. We could save a new set of blank data. But should this create a new page revision? I would argue no. But am I right?

Also how do we actually do this? We would need to use the old assignment and find all pages matching the assignment, then check if they have currently saved data for the old assignment and then overwrite it.

**Comment by stvoigt** [comment]
I have forgotten how we make the assignment. Could you place describe this again? Sorry ;)

**Comment by splitbrain** [comment]
Like this (in the Admin interface):

![struct schema assignments test wiki](https://cloud.githubusercontent.com/assets/86426/13279360/713e07be-dad7-11e5-9379-9d0ee1f1cd69.png)

**Comment by stvoigt** [comment]
Thanks. What about the other way round (Just thinking aloud): Defining the assigment within the page. Like: <struct: schema> (or as a dialog in the schema-editing section, but putting some additional syntax into the page). Then deleting the assignemt would make a page revision. 
This definition within a page could override the assignment in the admin section.
(I am not sure, if only admins should make assignments possible... Admin is alway bottleneck :-) )

I do think, that a new page revision is usefull, even in your suggestion. If you filled a data into schema for a certain page but another user/admin deletes the assignment (maybe on namespace level), you like to see, that there were data connected with your page. Am I right?

**Comment by splitbrain** [comment]
I think the Schema and Assignment editors will be made available to managers, but I think that decision hasn't been made, yet. Would be worth discussing in a separate ticket: #31.

I see what you mean, but it's complicated. let me list a few givens...

1. we do not have an assignment history
  1. we always show only values of the current assignment setup
  2. even when you look at an old revision only the data matching the current assignment is shown
2. we do not use assignment info when searching for data
  1. we simply look for all currently saved data matching the requested fields and filters
  2. when there's data for a page we assume its correct and the schema is actually assigned to that page

2.ii is why this ticket exists. Once a page is no longer assigned, the data is still there and would still be found when searching. So the data needs to be overwritten.

**Comment by splitbrain** [comment]
Now thinking about it, there is a big problem: the way I suggested to handle this would be very problematic in the following case:

Let's say I have an assignment pattern named ```foo:bar:*```. Now I delete that pattern and then add ```foo:**``` instead. They way I suggested to handle assignment deletions all data would be gone for all the pages in foo:bar:.

**Comment by splitbrain** [comment]
I think, the proper solution is to fix the problem at point 2. Eg, take assignment info into account when searching for data. To do that we have to rework assignments.

We need a table where we can easily read out the page name and its assigned schemas. This table would then be joined with the requested data, filtering out all non-assigned data. As soon as the same schema gets assigned again, the old data is back again.

**Comment by stvoigt** [comment]
I think I've got the point. No more feedback needed, right?

One think that comes to my mind: we should have a dialog that makes clear that all assigned data gets lost, when deleting a pattern. Maybe a list of all existing pages, connected with the pattern and containing data should be listed in this dialog too?

**Comment by splitbrain** [comment]
With the new table, data is not lost when the assignment is removed.
