### ISSUE TITLE
Refer to a struct field from a particular page.

### ISSUE THREAD

**Issue by cjohnsonuk** [cosmocode/dokuwiki-plugin-struct#293]
I use bureaucracy to create a new page in a name space with a struct schema assigned.  I'd also like the data submitted in a form to be included in the page itself I can get to work with placeholders in the template but when the struct data is updated the template is not, which I understand.
So I've set my bureaucracy form to create a page with a specific name (datapage) in a new namespace (based on a form field) to hold the struct data, (the schema allocation uses a reg exp to only match on this page name).  The form also adds another page in the same namespace as the struct page (mailmerge page) where I want to use the data from the associated struct page.
-- form (creates namespaceX and sub pages)
--namespace1
   |-datapage
   |-mailmerge page
--namespace2
   |-datapage
   |-mailmerge page
etc.

Mailmerge page would be something along the lines of

Dear {struct>.datapage:schemaname.firstname} {struct>.datapage:schemaname.lastname},
Thank you for your recent interest in {struct>.datapage:schemaname.productX}

where datapage is the name of the page, schemaname is the name of the schema on that page etc...

What I can't work out how to do is pull the information from the datapage in the same namespace to display inline with the rest of the text.

**Comment by iainhallam** [comment]
If I understand this correctly, @cjohnsonuk, you can now do this without the mailmerge pages by using Struct value aggregations on the same page as the data, which has the form `{{$schema.field}}` (looks up data in the current page) or `{{$page.schema.field}}` (looks up data in the named page).
