### ISSUE TITLE
Better Date-Picker

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#296]
The current date-picker does not allow directly selecting the year. Currently, selecting the birthday of a 50-year-old person requires 600 clicks on the Back-Button.

**Comment by cjohnsonuk** [comment]
and it doesn't allow selection of time for date time fields...
A "now" button would be nice to include date and time.

**Comment by stvoigt** [comment]
If you work on the date-picker, please check if it works with all other types in one schema. Currently I have one schema where the date picker works and a different one, where it does not work. If you are interested in my schema definition, please let me know. (The picker does not react on selecting the specific date, i.e. nothing happens.)

**Comment by micgro42** [comment]
@stvoigt Yes, your actual schema definitions would be useful. However, what you describe here sounds like a new/different problem.
Your browser is relevant as well.

**Comment by stvoigt** [comment]
okay, i will open a new issue for that...
