### ISSUE TITLE
Add Link-Text config-option to URL-type

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#298]
As suggested by @kossmac, it would be helpful to have a config option for the URL type where we can specify the link text, i.e. the text between the `<a>` `</a>` tags. I'm thinking about a placeholder which defaults to the entered text and to which more text can be added.

It might also be an option to add placeholders for pre- and postfix config options in order to reproduce the current behavior without duplicating entered data.

**Comment by SCarter2020** [comment]
Hi! Yes, i we need this.

**Comment by splitbrain** [comment]
I think c7273e8ec487f73f5c1524aab717508691a1d015 should be enough to satisfy this issue.
