### ISSUE TITLE
Add custom output loops

### ISSUE THREAD

**Issue by tiagoad** [cosmocode/dokuwiki-plugin-struct#301]
Perhaps a way should be added to loop over each row that matches a certain filter and output some data according to each field.

For example, I am using the plugin to document machines in a network. 
Each machine has an Hostname field, and I want to build a table that shows each machine's IP 
address, resolved from this name.  
Right now what I'm doing is using the [DNS Resolver Plugin](https://www.dokuwiki.org/plugin:dnsresolver) and creating a new Wiki field named IP Address with prepend `<dns>` and append `</dns>`. I would like to be able to build this table in a saner way, without having to create extra fields. Perhaps by defining something that would be repeated on each iteration like `@Hostname@: <dns>@Hostname@</dns>`

I'm not sure what the best syntax would be for something like this.

---

Another solution to this particular problem (but not to all of those that would be fixed with this feature) would be to add processed fields that can reference other fields. I would create a Processed Wiki field with some value like `<dns>@Hostname@</dns>` and it would be shown as such.

**Comment by splitbrain** [comment]
I think this should be implemented by additional plugins creating custom types. Eg. you could have DNS type that accepts an IP as input and outputs the DNS name. See https://www.dokuwiki.org/plugin:struct:devel#registering_new_types
