### ISSUE TITLE
Make Assignments and/or Schema available to managers?

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#31]
The current implementation gives access to Admins only, but I'd think it would make sense to open this up to managers.

**Comment by stvoigt** [comment]
At least the person who sets up the "documentation-project" in the wiki (e.g. project manager, scrum master) should be able to edit. But this person does not have to have admin rights. Do managers have access to the admin menu?

**Comment by splitbrain** [comment]
Yes, that's the point see https://www.dokuwiki.org/config:manager

**Comment by stvoigt** [comment]
IMHO we should give managers the access to schema editor/assignment.
