### ISSUE TITLE
Title alignment when using select fields with Bureaucracy is not ideal 

### ISSUE THREAD

**Issue by psy-q** [cosmocode/dokuwiki-plugin-struct#317]
The recent PR #308 has fixed a lot of issues when usint struct fields in Bureaucracy forms. But the input titles appear to be vertically oriented on the bottom in some cases at least:

![image](https://user-images.githubusercontent.com/87557/27423472-f6b76e3a-5731-11e7-87fd-06400d12cff3.png)

So you'd think the groups in the select field ("Betrieb 1", etc.) have no title at all and that "ITZ-Gruppen" is the title for the help text "Hold CTRL or CMD to select multiple values."

Is this something to do with the struct plugin? With non-struct Bureaucracy fields, they titles appear top-aligned.

**Comment by zarhan** [comment]
Hi,

  I  fixed this by adding 

`        vertical-align: top;
`

  to style.less for

.dokuwiki form.bureaucracy__plugin div.field
span.input style.

Line 113 in my file.

**Comment by psy-q** [comment]
Perfect now, thanks! :+1:
