### ISSUE TITLE
Make pattern/schema reusable

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#32]
I think for managing different project wikis (see farming concept) it would be helpfull to reuse pattern/schema between different wikis in one farm. I am not sure, if this is feasable, but I see the following options:
- make schema exports: maybe the sql-statements needed to create/change the tables
  - allow imports via the sqllite-interface
- manage schema within the animals but make it readable and distributable by the farmer
  - allow the animal to use and override the schema
- manage schema by the farmer and give an option "use in animal"

**Comment by splitbrain** [comment]
I guess schema import/export is the easiest thing. Since the sqlite table lies within the data directory there's no easy way to share that between animals.

**Comment by stvoigt** [comment]
If no sharing between animals is possible we should make an import/export thing.

**Comment by splitbrain** [comment]
This was not meant to be done in this sprint, but I need the import mechanism to simplify testing. So now we have schema import/export with a nice interface :-)
