### ISSUE TITLE
Feature Wish: Make struct data available to site search

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#322]
It would be nice to have the struct data integrated into the DokuWiki search.  See also #309.

**Comment by splitbrain** [comment]
pageschema data should already be in the search. See https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/action/search.php

**Comment by fthommen** [comment]
The feature wish referred to all struct data, this includes lookup schema.
