### ISSUE TITLE
In-line editing of aggregated table causes "ajax.php:67" error.

### ISSUE THREAD

**Issue by TheKojukinator** [cosmocode/dokuwiki-plugin-struct#326]
![image](https://user-images.githubusercontent.com/30471780/28732162-dc5abfc6-73a4-11e7-8254-8c26aebc5767.png)
I have an aggregated table above. The title column is a page, and the other linked ones are tags. Auto-complete works fine when editing the form on the respective pages. However, when I try to in-line edit, when the auto-complete triggers I get an error like so...
![image](https://user-images.githubusercontent.com/30471780/28732239-273b943e-73a5-11e7-959b-c2488715ef40.png)
Here is my console log from Chrome Version 60.0.3112.78 (Official Build) (32-bit)...
[rtfm.kojukination.com-1501268309225.txt](https://github.com/cosmocode/dokuwiki-plugin-struct/files/1184018/rtfm.kojukination.com-1501268309225.txt)
I tested this with both CDN jquery loading, and local, same thing happens, but I left it on local for now just in case.

Let me know if I can provide anything else to help troubleshoot.

Thanks,
Steve

**Comment by shieldwed** [comment]
I do have the same issue since upgrading from `2017-06-15` but I'm also experiencing the same issue on a brand new (today, 2017-12-26) installation of DokuWiki.
