### ISSUE TITLE
Feature: Tag fields by default show all pages with that tag

### ISSUE THREAD

**Issue by isoboroff** [cosmocode/dokuwiki-plugin-struct#346]
This is a feature request.  I can try and write the patch if some helpful soul tells me where to start.

There is a 'tag' datatype.  By default, the tag is rendered as a link to a page with the name of the field.  What I'd like to have is to have it link to a page containing the aggregation of all the page titles for pages with that tag field's **value**.

It's like the page would contain:

    ---- struct list ----
    schema: myschema
    cols: %title%
    filter: tagfield = tagvalue
    ----

But I can't figure out how to pass `tagvalue` along.  You can't use the $STRUCT.schema.field$ syntax because the value we needed is on the prior page.

**Comment by isoboroff** [comment]
Closed this, I'm an idiot.

**Comment by berlindave** [comment]
Maybe I'm also an idiot. But I'm interested in the solution of the problem …
