### ISSUE TITLE
Feature Request: Encryption of data

### ISSUE THREAD

**Issue by charlykwr** [cosmocode/dokuwiki-plugin-struct#348]
It would be very helpful if data optionally could be encrypted and decrypted (on client side, similar to plugin dokucrypt2). Then it would be safe to store data containing personal informations, account numbers, mail addresses, passwords, and so on also on installations on servers hosted in the internet.

**Comment by splitbrain** [comment]
Yeah, sorry this is beyond the scope of this plugin. Supporting that would add a major mental overhead to an already complex plugin.
