### ISSUE TITLE
Question about syntax

### ISSUE THREAD

**Issue by jschaeff** [cosmocode/dokuwiki-plugin-struct#352]
Hi,

this might be a stupid question ... after reading the doc and having some tries, I could'nt find the syntax to make a "struct" data in my pages ...

I tried several things like:

```
---- struct myschema ----

----
```

or

``` 
---- struct ----
schema: myschema
----
````

nothing did the trick.

```
---- struct lookup ----
----
```
works ...

**Comment by splitbrain** [comment]
There is no syntax. That's the point of this plugin. When a schema is assigned to a page, the editor will show fields to fill in data when editing the page.

**Comment by jschaeff** [comment]
Thank you, the reason I was'nt able to see anything is because my assignements where wrong.

Great plugin, thank you !
