### ISSUE TITLE
how to filter to select items that have empty fields?

### ISSUE THREAD

**Issue by macneurolab** [cosmocode/dokuwiki-plugin-struct#358]
Hello, I am trying to list in the table all items in which the fields GROUP and SUBGROUPS are both empty (these are lookup fields in case that matters). This does not seem to work. Any alternative? 

---- struct table ----
schema  : animals
cols     : ExpName, Strain, Group, Subgroups, DOB
filter   : Group =
filter   : Subgroups =
rownumbers: 1
csv: 0
----

It actually works if the field is a DATE. In that case if you use only as a filter
filter  : Date = 
it will list items in which the date field is empty.  But it does work for the other field types.  How can you filter to select items that have nothing in the fields?

**Comment by solewniczak** [comment]
Try: 

`filter: Group =* ^$`

**Comment by macneurolab** [comment]
Hi, 
Thank you very much for this answer. This works for fields that are defined as SINGLE-Input, but not for fields that are defined as Multi-Input. Is there a code that would work if the field GROUP is defined as Multi-Input?

**Comment by macneurolab** [comment]
Upon further testing it appears that the problem in not that the field is defined as Multi-input. The problem occurs when the field is defined as a LOOKUP of a LOOKUP schema.  The first image shows the code i used for atest (LinktoField is a LOOKUP type field targeting a LOOKUP schema):

![image](https://user-images.githubusercontent.com/34627480/36156067-076e1004-10a4-11e8-9662-0774bd1cc59e.png)

Here is the result:

![image](https://user-images.githubusercontent.com/34627480/36156156-48d0fd4a-10a4-11e8-81f9-ffef11865b0e.png)

Notice that there are 2 empty fields at the bottom of the TABLE in LinktoField. But the filtered TABLE at the top shows "Nothing Found" when it should have shown these 2 rows.
