### ISSUE TITLE
multi-checkbox preview broken

### ISSUE THREAD

**Issue by rottaran** [cosmocode/dokuwiki-plugin-struct#364]
When using a multiple-input checkbox on a page schema, editing the page and hitting preview seem to transfer just the last selected checkbox instead of all selected checkboxes. At least struct_schema_data in the form post parameters looks wrong.

**Comment by annda** [comment]
I cannot reproduce the bug with the stable release of Dokuwiki and the latest struct plugin. @rottaran If you are still having this issue, can you provide more details?
