### ISSUE TITLE
Color Type Default Value

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#367]
When I use the Color Type in my struct schema and define a default vaule it will not effect anything. As mentioned in the documentation, the value will not be saved. But how is it possible to set this default value? Even if I edit my page and want to change the color, I only can see it in the edit mode (not in view mode). ==> see screenshot
![grafik](https://user-images.githubusercontent.com/2620833/34615627-d34daae6-f235-11e7-9860-a12871cc8181.png)
If I want to select the default value (click on the color, choose the color and hit okay) nothing changes.
![grafik](https://user-images.githubusercontent.com/2620833/34615828-71d0e1e2-f236-11e7-89a6-c73718d400c8.png)
I thought, I can use the default value to select it much faster. But the only thing I can use the default value for, is to exclude that color.

**Comment by splitbrain** [comment]
Hmm yes, I guess the name "default color" is a bit misleading. It's the color that is used to signify that no color has been selected.

**Comment by stvoigt** [comment]
Okay, I see. But is it wanted, that you cannot pick that "default color"?
