### ISSUE TITLE
Time values are not saved in chrome browser

### ISSUE THREAD

**Issue by Nitramakloh** [cosmocode/dokuwiki-plugin-struct#373]
This issue occurs in DateTime fields with public version from 2018-01-18. No matter which value I enter, it is only stored as "0:00". This happens in chrome 63.0.3239.132.
![image](https://user-images.githubusercontent.com/35602186/35154106-347d5af2-fd29-11e7-9937-892f2b4a7d79.png)

EDIT: Tested it again with Firefox 58 and there it works fine. Any idea what can be the reason?

**Comment by Nitramakloh** [comment]
I've found a workaround for my site. The only solution for me was to set the html form input type from "datetime-local" to "text", as shown below:

`public function valueEditor($name, $rawvalue, $htmlID) {
		date_default_timezone_set('Europe/Berlin');
		
        if($this->config['prefilltoday'] && !$rawvalue) {
	    $rawvalue = date('Y-m-d H:i:s');
        }

        $params = array(
            'name' => $name,
            'value' => $rawvalue,
            'class' => 'struct_datetime',
            //'type' => 'datetime-local', // HTML5 datetime picker
			'type' => 'text',
            'id' => $htmlID,
        );
        $attributes = buildAttributes($params, true);
        return "<input $attributes />";
    }`

**Comment by micgro42** [comment]
Thank you for that bug report 🌸. It should work again after #374 is tested and merged.
