### ISSUE TITLE
Cloud filter does not select correctly if table filter has OR (filteror)

### ISSUE THREAD

**Issue by macneurolab** [cosmocode/dokuwiki-plugin-struct#378]
If you have this line below (filteror: source = CR) the CLOUD is unable to filter the table correctly by the selected item in the cloud. If you remove the Filteror line it works fine. So you cant have a table listing mutiple items included in a field (in this case CR and Jax) and then use the cloud to filter based on another field. 

```
---- struct cloud ----
schema: Animals
field: IACUC
---- 
---- struct table ----
schema: Animals
cols: ExpName, Source, DOB, Arrival, Death, IACUC
head: Animal, Source, DOB, Arrival, Death, Protocol
filter: source  = Jax
filteror: source = CR

rownumbers:1
summarize:0
dynfilters:0
CSV:0
----
```

**Comment by fthommen** [comment]
This generally applies to dynfilters

**Comment by fthommen** [comment]
Hello, is a solution/fix to this quite old bug foreseeable?  It bites us every day, as we have several such aggregations where users are not able to properly search through.  I'm willing to help with testing, but unfortunately I will probably not be able to help with coding.

**Comment by fthommen** [comment]
I would be prepared to give it a try to fix this over two year old bug myself. But - given my limited knowhow of PHP and the DW framework - I'd require some "startup" hints: Which files(!) within the plugin would I need to have a look to?  I will be ableo to navigate from there.  I just need the starting point.

**Comment by fthommen** [comment]
Any chance that this will ever be fixed?

**Comment by fthommen** [comment]
Still open after over four years and biting us every day.  Is there anything I can do to support the developers in fixing this issue? As I said in https://github.com/cosmocode/dokuwiki-plugin-struct/issues/378#issuecomment-633233523 I'm willing to give it a try, but I _do_ need some startup hints, as I am quite lost in the DW PHP framework.

**Comment by splitbrain** [comment]
Analysis results

This is easy to explain. Dynamic filters are handled here: https://github.com/cosmocode/dokuwiki-plugin-struct/blob/fb2252eac3382a79b6feb00e14ea0d13e5b4bfd4/meta/SearchConfig.php#L57-L58

Basically all dynamic filters are added to the existing fixed filters: https://github.com/cosmocode/dokuwiki-plugin-struct/blob/fb2252eac3382a79b6feb00e14ea0d13e5b4bfd4/meta/SearchConfigParameters.php#L217-L223

But when the fixed filters use an OR filter, the result is basically this: `(fixed1 OR fixed2 AND dynamic1)` which is of course wrong. The correct result would be `((fixed1 OR fixed2) AND dynamic1)`.

Fixing this bug essentially needs to treat fixed and dynamic filters separately and add them in their own subgroups where clauses here: https://github.com/cosmocode/dokuwiki-plugin-struct/blob/fb2252eac3382a79b6feb00e14ea0d13e5b4bfd4/meta/Search.php#L513

I guess it would make sense to get rid of the `updateConfig` method and instead handle the dynamic filters directly in `Search`. This might have side effects though... #609 might profit somewhat from adjusting this.
