### ISSUE TITLE
Image type is actually MediaType

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#38]
Currently (local?) videos and audio files seem to work as well within the image type. I guess we should either enforce a check on the mime-type or rename the type to media.

This has been introduced by #13 and #26.

**Comment by splitbrain** [comment]
Good point. I guess it makes sense to rename it to media. Maybe we could introduce an optional config to restrict the field to a certain mime-type.

**Comment by stvoigt** [comment]
I like that media-type. I does work with pdf as well. The problem than is only, that you cannot open it, because this "slideshow/gallery" style pops up and tries to display an image or something like that...
