### ISSUE TITLE
[bug] Filter all empty text fields

### ISSUE THREAD

**Issue by solewniczak** [cosmocode/dokuwiki-plugin-struct#380]
The commit [dc7d8d082c](https://github.com/cosmocode/dokuwiki-plugin-struct/commit/dc7d8d082cb181a94e6a0cfbb7c5c1909d40d696#diff-af4b12df036ac2f7f1c4e5258686bb7c) has introduced a new logic that joins every filter rule for Text, LongText and Wiki column types with "isn't empty" constraint. I'm not quite sure what was the intention but this broke the simple empty search for text types. Let's have a look at the example. Imagine that we have schema `someschema` with two columns: `col1` and `col2`. `col1` is `Text` type.
```
---- struct table ----
schema: someschema
cols: col1, col2
filter: col1=
----
```
The above code should return all rows that have `col1` field empty but instead we get empty result. This is caused by the additional constraint added by `dokuwiki\plugin\struct\types\TraitFilterPrefix` trait which leads to final SQL that look like this:

`SELECT  [...] AND ( ( someschema.col1 != '' AND someschema.col1 = '' ) ) ) [...]`

The empty filter works fine for other column types that don't use the trait (not testes with multi types yet).

I'm not quite sure how should I fix it since as I've mentioned before, I'm not certain what was the idea behind it. Can you explain it to me, so we can find a solution that will fix that bug.

Connected with #358

**Comment by Chris75forumname** [comment]
Thanks to @solewniczak, I used this info for a hack, shown here:
https://forum.dokuwiki.org/d/21420-struct-checkbox-field-becomes-nul-when-unchecked-filter-fails/9
It works for me! Cheers!

**Comment by annda** [comment]
After some discussion with @splitbrain we have decided to remove from queries the problematic limitation in dc7d8d082c  (i.e. when using filters, always discard empty fields from the result set).

That behavior was introduced to eliminate unwanted results in case of filter applied to a field with a pre- or postfix. When searching for a string that matched the pre- or postfix, all empty fields were returned as well.

After removing the filter, searching for empty string should work again as expected. Pre/postfixes fields are "broken" again, but handling that case properly without side effects is rather tricky and it will take some time to implement a solution.
