### ISSUE TITLE
Dokuwiki breaks on installation of struct

### ISSUE THREAD

**Issue by SB401** [cosmocode/dokuwiki-plugin-struct#381]
My wiki breaks everytime I try to install struct giving a 500 error. Deleting the struct folder from the pluggin folder through the control panel fixes the problem.

**Comment by kasimon** [comment]
I think I had this once when installing struct on a too old version of dokuwiki. Also, do you have the sqlite plugin installed?

**Comment by micgro42** [comment]
Yes, that sounds like a too old PHP and/or DokuWiki version.

Can you also have a look at your PHP Error Log?
