### ISSUE TITLE
Add a simple way to exlude start.txt from namespace schema assignements

### ISSUE THREAD

**Issue by kasimon** [cosmocode/dokuwiki-plugin-struct#383]
When mapping schemas to namespaces, we usually want to exclude the start.txt of that namespace from the metadata mapping, as we use iit for listing the namespace's entries and at least in our case it doesn't make sense to attach struct data to it.

**Comment by splitbrain** [comment]
I wonder if this should be hardcoded to the start page or if assignment rules should have excludes.

**Comment by kasimon** [comment]
What about a wiki-wide plugin setting?

**Comment by annda** [comment]
What about a simple exclude rule, for example comma separated pages, like `start,info,latest,overdue`?

**Comment by annda** [comment]
I just checked and this is already possible without any changes in code, just by using regex to define schema assignments, like this: `/mynamespace:(?!foo)(?!bar).*/`, which excludes pages foo and bar from struct.
Should I submit a PR with an additional hint in the admin interface?

**Comment by splitbrain** [comment]
I guess some examples in the documentation should be enough.

**Comment by kasimon** [comment]
> I just checked and this is already possible without any changes in code, just by using regex to define schema assignments, like this: `/mynamespace:(?!foo)(?!bar).*/`, which excludes pages foo and bar from struct.

Nice find, thank you. Not the most accessible way to set up this, but the result should be fine.

**Comment by annda** [comment]
I added an example to the documentation: https://www.dokuwiki.org/plugin:struct:assignments#struct_pluginassignments

**Comment by kasimon** [comment]
Awesome, thank you!
