### ISSUE TITLE
Using single struct fields in the wiki page

### ISSUE THREAD

**Issue by abecede753** [cosmocode/dokuwiki-plugin-struct#391]
I also posted this question on stackoverflow, but it did not get a lot of attention, so also posting here:

The plugin is nice for managing structured data. But so far the only way I found to present the data for one single entry is a simple automatically generated table at the top of the page followed by the content of the entrys wiki text. Since I need the single entry pages to look better, I want to replace the simple table with something more pleasing to the eye like a template page that gets included into the page itself using `{page>_mytemplate}`.

The `mytemplate` wiki page might look like this:

    ==== STRUCTFIELD_TITLE ====
    
    The STRUCTFIELD_NAME is a STRUCTFIELD_CLASSIFICATION consisting
    of STRUCTFIELD_INGREDIENTS.

"`STRUCTFIELD_*`" should be replaced with the fields defined in the schema of course. 

---
The wiki page of the single entry should include the template page as mentioned above with `{page>mytemplate}`.

So my question in essence is: How to include single fields of a schema into a wiki page as template variables, and can this be further automated using one "template wiki page" that gets included via the `{page>...}` command?

**Comment by iainhallam** [comment]
There's a working solution in #145 but the PR hasn't been merged yet.

**Comment by abecede753** [comment]
Thank you. I'll follow #145 which looks very promising.
