### ISSUE TITLE
Entering new values prompts Error with Line 369 on meta/AggregationTable.php

### ISSUE THREAD

**Issue by OezDur** [cosmocode/dokuwiki-plugin-struct#398]
I just installed struct and get an error message everytime I add an entry to the lookup table.
I tested different tables, pages, deinstalled- and reinstalled struct + sqlite plugin but it doesnt help.

I get the error after entering a value to a table like this one:

```
---- struct lookup ----
schema: test_db
cols : name
dynfilters : 1
csv : 0
----
```

Errormessage:

`Warning: Invalid argument supplied for foreach() in _mypathtodw_\dokuwiki\lib\plugins\struct\meta\AggregationTable.php__ on line 369`

It seems like struct and/or sqlite dont get completey deinstalled. What folders do I have to delete to achieve that?

**Comment by BeepBoopBuup** [comment]
I "solved" the problem by installing version 2018-04-24 .

The Version that didn't work was the 2018-05-22 .

I have no clue why that changed it but it did.

**Comment by 3615pipou** [comment]
I've got the same problem with the version 2018-10-08

**Comment by blakskyy** [comment]
I am getting this same error on 2018-10-08

**Comment by kdmoyers** [comment]
I'm getting it too, on version 2018-10-08.  Very frustrating.
reloading the page makes the error go away.

Wrapping the foreach loop in a "if (sizeof($row) > 0) { }" statement makes the error go away, but it still doesn't show the newly added data.

**Comment by micgro42** [comment]
Turns out: I also introduced this bug in ff2afc7c7bdf9f04b6bc2917af42ff865757c54d 😇
