### ISSUE TITLE
information request: migration from data plugin

### ISSUE THREAD

**Issue by asheenlevrai** [cosmocode/dokuwiki-plugin-struct#402]
Hello,

Our wiki heavily relies on the data plugin (together with the bureaucracy plugin) and I noticed just now that the struct plugin is currently recommended instead.

Is there any way to "_easily migrate_" from one to another or does it require to rewrite most of our wiki?

Thank you very much in advance for your help.

Best,
-a-

**Comment by splitbrain** [comment]
There is no such tool currently. See #42
