### ISSUE TITLE
CSV-export with semicolon instead of comma

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [cosmocode/dokuwiki-plugin-struct#416]
Hi,

the usual separator for CSV files varies by country. For example, in the German Office version commas are not interpreted directly, because here the semicolon is defined as separator. Therefore a country-dependent configuration would be useful

Regards
Juergen

**Comment by micgro42** [comment]
Thank your for your feature request. However, we won't implement it. Every software that imports csv-data should be able to handle comma separated values (csv).
LibreOffice offers a dialog that lets you select the separator when opening `.csv` files and I would expect MS Office to do something similar.

**Comment by Juergen-aus-Koeln** [comment]
The german MS-Excel doesn't import this !!!!

In companies normally Microsoft Office is the favorite office program, not OpenOffice or LibreOffice. And then the only way to handle this with Excel is to load the csv file, open the text import utility for the whole text, manually define the comma as separator instead of the semicolon and then let the utility split into columns. For a "normal" user this is much too complicated. 

So if semicolons are not supported by the struct plugin, this csv-export function most probably will be used very seldom.

**Comment by micgro42** [comment]
I just tried this at a colleague's Windows Excel and can confirm that correctly opening this with MS Excel is not obvious. Please file a bug with Microsoft, this is an issue at their end.

**Comment by Juergen-aus-Koeln** [comment]
There are many requests and suggestions for this on the net, among others also directly with Microsoft. 

One suggestion: 
A simple possibility would be to insert a top line with the syntax "sep=," in the csv file.  This way Excel recognizes the separator. However, I cannot check whether this would also be processed by other Office programs.

**Comment by splitbrain** [comment]
CSV is defined in RFC 4180 (see https://tools.ietf.org/html/rfc4180). You're suggested top line is not supported in that and would create an extra line in all compliant CSV processors.

**Comment by Juergen-aus-Koeln** [comment]
Ok, only an idea!
