### ISSUE TITLE
struct header missing on pages created by bureaucracy -- root cause identified!

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#424]
## The Issue

There exists the stubborn issue that pages created via a bureaucracy template action with struct data don't have the usual struct header rendered when first opened. This issue exists basically since the very beginning of struct, when we added bureaucracy support.
There were several attempts to fix this before, especially by @solewniczak in eaab469c00cfe321e34b8028f8f0004daa52b91e and #355, but the problem still persists and the current code generates PHP Warnings 😕.

## The Cause
I have now finally tracked its root cause:

The bureaucracy template action adds an invisible iframe calling `do=export_html` for every created page:

```php
        foreach ($pages as $ID) {
            // indexerWebBug uses ID and INFO[exists], but the bureaucracy form
            // page always exists, as does the just-saved page, so INFO[exists]
            // is correct in any case
            tpl_indexerWebBug();

            // the iframe will trigger real rendering of the pages to make sure
            // any used plugins are initialized (eg. the do plugin)
            echo '<iframe src="' . wl($ID, array('do' => 'export_html')) . '" width="1" height="1" style="visibility:hidden"></iframe>';
        }
```

See https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/blob/519ab560298fa550e3a2dcd13f3e1dbfc1de163f/helper/actiontemplate.php#L318-L327

However, our struct syntax rendering refuses to render on anything other than the `show` action:
https://github.com/cosmocode/dokuwiki-plugin-struct/blob/8ddbe81a4f5a042937b16b87490bed472f61995b/syntax/output.php#L86-L88

Thus the render's xhtml output is cached without the usual struct header.

## Possible Solutions

I see three possible ways to resolve this:

- have the bureaucracy iframe request the `show` action (not sure if this will break anything)
- have the struct output render on `export_html` as well
- adjust DokuWiki core to not cache the xhtml output for any actions other than `show`

@splitbrain Any ideas which approach would be best to implement?

**Comment by splitbrain** [comment]
I think making struct render in `export_xhtml` makes most sense?
