### ISSUE TITLE
"date('Y-m-dTH:i');" should be "date('Y-m-d\TH:i');"

### ISSUE THREAD

**Issue by hokkaidoperson** [cosmocode/dokuwiki-plugin-struct#427]
https://github.com/cosmocode/dokuwiki-plugin-struct/blob/12ce640443fbda6da53617201d6cedf4b8bb5eb3/types/DateTime.php#L42
This line should be "$rawvalue = date('Y-m-d\TH:i');", not "$rawvalue = date('Y-m-dTH:i');", or the character "T" is replaced to the time zone (such as "JST") and the value property of datetime-local becomes invalid.

Shall I send you a pull request?

**Comment by glensc** [comment]
There's also some code like:
- https://github.com/cosmocode/dokuwiki-plugin-struct/blob/7c5e950485dcf89cfb81f37bab4426ec558510ca/types/DateTime.php#L68

so send the PR, but test that all changes are still ok.
