### ISSUE TITLE
Dynfilters with user column

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [cosmocode/dokuwiki-plugin-struct#435]
Hi,

I am using an aggregation with a struct table that contains some columns of type "user". If I want to apply the dynfilter to these columns, I cannot filter by the real name, although this real name is specified in the output. Instead, I need to get the wiki login name and write it into the field. In particular, this is bad if the name contains German umlauts.

Best regards
Jürgen

**Comment by splitbrain** [comment]
The user type would need adjustments to the filter creation to also look at the full name.

**Comment by annda** [comment]
Users' full names are not saved in the database. In order to get them, we would have to separately query the authentication backend, which is not feasible at this point.
