### ISSUE TITLE
Can't delete all data in a multiple field of a lookup schema

### ISSUE THREAD

**Issue by moz0817** [cosmocode/dokuwiki-plugin-struct#439]
If you have a field (i.e. type text) with **multiple** values checked, it's not possible to delete all values **inline**. The editor wants at least one character, otherwise you get the old value(s).

**Comment by moz0817** [comment]
I forgot that this behavior apply only for lookup schemata.

**Comment by Mutanarq** [comment]
The same issue, make a correction, please :-)
(Example: Used 10 values from the list, then deleted first 7 from these 10 and no chance to delete last 3 to be on 0 selected).
