### ISSUE TITLE
Fatal error if sqlite plugin is installed but neither pdosqlite nor sqlite 2

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#440]
_Originally posted by @graceful-phoenix in https://github.com/cosmocode/dokuwiki-plugin-struct/issues/313#issuecomment-467017744_

A month ago I was trying openSUSE Linux, I had DokuWiki installed there from a tarball, and it worked smoothly with sqlite and struct plugins installed.
Now I returned to Ubuntu Linux (18.10), and installed DokuWiki from the very same tarball (it was backed up), had it set up with Nginx (1.15.5) and php7.2-fpm (from packages). It worked until I installed struct and sqlite plugins through the Extension Manager. Blank page immediately, I did not even had a chance to use the plugin in any way. I see this error in /var/log/nginx/error.log:

```
2019/02/25 15:59:53 [error] 29751#29751: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /var/www/html/dokuwiki/lib/plugins/struct/helper/db.php:38
Stack trace:
#0 /var/www/html/dokuwiki/lib/plugins/struct/helper/db.php(22): helper_plugin_struct_db->init()
#1 /var/www/html/dokuwiki/inc/plugincontroller.class.php(109): helper_plugin_struct_db->__construct()
#2 /var/www/html/dokuwiki/inc/pluginutils.php(45): Doku_Plugin_Controller->load('helper', 'struct_db', false, false)
#3 /var/www/html/dokuwiki/lib/plugins/struct/meta/PageMeta.php(20): plugin_load('helper', 'struct_db')
#4 /var/www/html/dokuwiki/lib/plugins/struct/action/title.php(42): dokuwiki\plugin\struct\meta\PageMeta->__construct('start')  
#5 /var/www/html/dokuwiki/inc/events.php(229): action_plugin_struct_title->handle_meta(Object(Doku_Event), NULL)
#6 /var/www/html/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')
#7 /var/www/html/dokuwiki/inc/parserutils.php(502): Doku_Event->advise_after()
#8 /var/w" while reading response header from upstream, client: 127.0.0.1, server: dokuwiki.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost"
```

Restarting the nginx and php7.2-fpm services doesn't help.
I manually removed the struct plugin, and DokuWiki local site is available again.
Installation from a tarball from the official site means that _I have relatively new (stable) version._

**Comment by graceful-phoenix** [comment]
Answer to your suggestion to install pdo-sqlite:

It is written on http://php.net/manual/en/ref.pdo-sqlite.php :
"The PDO_SQLITE PDO driver is enabled by default."

I see in the list of installed php extensions (php -m): "PDO". 

I can't find anything like the name of this extension in Ubuntu packages (packages with php extensions have the form "php7.2-*".

I tried installing some relevant packages one by one, restarting php7.2-fpm service each time and checking the site.
php-db, php7.2-dba packages did nothing.
Finally, I tried php7.2-sqlite3. Now it works.

One more thing: when I installed DokuWiki in openSUSE, I launched install.php first, which obviously checked all prerequisites. But with this installation, I forgot this step, restored recommended folders from the backup and started to use the site immediately (it worked as expected until installation of struct plugin).
If this is about a missing prerequisite of DokuWiki core, then there was no error shown (I saw error messages or warnings when other php extensions were missing).
