### ISSUE TITLE
What to do when database disk image malformed?

### ISSUE THREAD

**Issue by GJRobert** [cosmocode/dokuwiki-plugin-struct#447]
I might have a corrupted struct database since I have got messages like these on my wiki start page:
```
HY000 11 database disk image is malformed:

REPLACE INTO titles (pid, title, lasteditor, lastrev, lastsummary) VALUES ('espy-transcribe','espy/Transcribe','ghsrobert','1554160263','shared')

HY000 11 database disk image is malformed:

REPLACE INTO titles (pid, title, lasteditor, lastrev, lastsummary) VALUES ('mac:os:homebrew','Homebrew','ghsrobert','1554171847','建立')
```

Should I just delete /data/meta/struct.sqlite3? Or should I try rebuild the database somehow? (I have not begun to entry data schema and entries so there should only be trivial page metadata in the file)

(How I isolate that the cause is struct plugin: I disabled struct for that animal, and the messages are gone)

**Comment by splitbrain** [comment]
You can try running the [PRAGMA integrity_check](https://www.sqlite.org/pragma.html#pragma_integrity_check) command on the database (through the sqlite plugin interface for example). However you should try to figure out what corrupted your database in the first place. Faulty hardware or power outages are a common reason.
