### ISSUE TITLE
Why are links of an aggregation in the metadata?

### ISSUE THREAD

**Issue by moz0817** [cosmocode/dokuwiki-plugin-struct#450]
Is it intended that links (of page-fields) listed in aggregations be entered as references in the metadata?
It does not seem to make much sense to me. In addition, in aggregations with limit, only the links of the first page are indexed. That makes even less sense ;-).

I think it would be good if this behavior (if any) could be turned on only when needed.

**Comment by moz0817** [comment]
It's not  a question - it's a bug. I will open a new issue.

**Comment by Juergen-aus-Koeln** [comment]
In my opinion this even makes a lot of sense, it has helped me a lot already.

Regards Juergen

**Comment by moz0817** [comment]
Can you please give me practical examples? Do you use this for both page and lookup schemata?
Please reply under (#467).

Regards Matthias
