### ISSUE TITLE
dokuwiki login page leaks struct plugin Information of closed wiki without being logged in

### ISSUE THREAD

**Issue by b3nks** [cosmocode/dokuwiki-plugin-struct#477]
My Wiki Release 2018-04-22b "Greebo" showed one of my struct entrees at the login page without being logged in. ACL of * is set to "none" for @ALL.
The leaked key value pairs box of struct could be found in the source in the Content Part:

```
    <div class="wrapper group">

        
        <!-- ********** CONTENT ********** -->
        <div id="dokuwiki__content"><div class="pad group">
            
            <div class="pageId"><span>start</span></div>

            <div class="page group">
                                                        <!-- wikipage start -->
                <div id="plugin__struct_output"><div class="table"><table class="inline">
<thead>
@@@LEAKED INFORMATION@@@
</tbody></table></div></div><p>Bitte hier anmelden: </p> <div class="centeralign"> <form id="dw__login" method="post" action="" accept-charset="utf-8"><div class="no">
```
Screenshot:

![72685380-d8f5cd80-3ae9-11ea-855d-cb8a3d5c6670](https://user-images.githubusercontent.com/20385436/72762600-85b27680-3be0-11ea-9916-cc3dad3142c1.png)

After having set cachetime to 10 seconds the leaked information immediately disappeared and did not reappear when setting it back to a higher value.

Up till now i could not find a way to reproduce, but it happened earlier in another instance of dokuwiki so the incidence cant't be a rare exception.

What I know is, that the entree was the newest entree of a certain pageschema created with a beaucracy form.

So reproducing seems to be:

- install dokuwiki greebo
- install struct and bureaucracy
- create a pageschema
- create a page with a form like

```
<form>
Action template lorem:ipsum:template lorem:ipsum:dolor:@@schema.fielda@@-@@schema.fieldb@@-@@schema.fieldc@@
struct_schema "schema" !
submit "create"
</form>
```

- fill out form and create page
- logout and see the added information on login page (with a bit of (bad) luck)

Something was conspicuous and might be mentioned. The leaked info just contains the box with the key value pairs and *not* the page content of the related page.

I guess we are looking for some temp or cache file, that by coincidence is included into the content part of a wiki page / login page.

After experiencing the issue I updated struct (latest) and bureaucracy (latest) now.
if it happens again i will do a full text search on dokuwiki root, to find the culprit.

This is really a nasty one, so let's weed it out.

**Comment by splitbrain** [comment]
I believe this has been fixed a while ago. If you can still reproduce the problem, please reopen.
