### ISSUE TITLE
A "date-link" type would be really useful

### ISSUE THREAD

**Issue by chrisisbd** [cosmocode/dokuwiki-plugin-struct#478]
It would be really handy if there was a "date-link" type which would create a link to a page with the date as part of its name.  Thus one would be able to create [links to] new pages for a specific date.

**Comment by annda** [comment]
This is a very specific feature. Struct types are meant for storing data. For data generation, give a try to the [bureaucracy plugin](https://www.dokuwiki.org/plugin:bureaucracy). It works well with struct.
