### ISSUE TITLE
migration hints from structured data plugin to struct

### ISSUE THREAD

**Issue by roadrunnerjb** [cosmocode/dokuwiki-plugin-struct#480]
Hi,
I'm trying to migrate from structured data plugin to struct plugin with about 2500 pages using **datatemplateentry** and **datatable** syntax. I did some tests and I miss some hints on howto perform the migration.  I saw #402 an d #42 which helped me but there is still one thing:

In datatable there are filtervariables like **%now%** to I filter in comparison to the current date. How can I achieve this in **struct table**  ?

The following is working:

```
---- struct table ----
schema   : miete
cols     : %pageid%, einheit, miete, ab_dt, bis_dt, nkvz
filter : ab_dt < 2020-02-03
sort : %title%
----

```
This one doesn't:

```
---- struct table ----
schema   : miete
cols     : %pageid%, einheit, miete, ab_dt, bis_dt, nkvz
filter : ab_dt < %now%
sort : %title%
----

```

Regards
Joachim

**Comment by splitbrain** [comment]
please see https://www.dokuwiki.org/plugin:struct:filters#value_placeholders - syntax differs from the data plugin
