### ISSUE TITLE
Bureaucracy : struct_field or struct_schema with lookup table => Wrong placeholder replacement

### ISSUE THREAD

**Issue by Vincent31Fr** [cosmocode/dokuwiki-plugin-struct#483]
Something wrong when trying to create page with action template (from bureaucracy plugin) with struct_field or struct_schema field. 
In the bureaucracy form, we can see the correct labeled value (inquire from lookup page editor) but when we click on submit button, the placeholder for targeted page seems to be replaced by the primary key (integer) instead of labeled value when refer to lookup table (work correctly with dropdown table)

**Dokuwiki** version: 2018-04-22b "Greebo"
**Bureaucracy** plugin version: 2019-10-28
**Sqlite** plugin version: 2019-03-20
**Struct** plugin version: 2020-02-04

Step to reproduce:
-	Create lookup schema (type text)
-	Populate lookup schema from page
-	Create page schema (type lookup which points to previous populated lookup schema)
-	In page, create bureaucracy form with struct_field or struct_schema fields setup with previous page schema (with action template)
-	Click on submit button 

The page name look like 1_2_1_1 insteat of "\<label1>\_\<label2>\_\<label1>\_\<label1>"

**Comment by Vincent31Fr** [comment]
@annda 
I have tested with last version of the wiki and plugins and have the same issue :
if needed, I can send you an archive with the context to reproduce anomali 

Dokuwiki version: rc-2020-06-09 "Hogfather" RC3
Bureaucracy plugin version: 2020-04-09
Sqlite plugin version: 2020-04-09
Struct plugin version: 2020-06-30

**Comment by annda** [comment]
@Vincent31Fr Yes, please post more background information, like the schema definitions and bureaucracy syntax. A sample of your struct data would also be helpful (CSV export).

**Comment by Vincent31Fr** [comment]
@annda please find attached an example :
1 schema  "folders" of type text, populate by "folder_definition" page
1 schema "new_page_schema" of type lookup (base on "folders" schema)
1 page "new_page" base on bureaucracy action template form with struct_field from  new_page_schema lookup

[context sample.zip](https://github.com/cosmocode/dokuwiki-plugin-struct/files/4895027/context.sample.zip)

**Comment by annda** [comment]
I can reproduce the error with your data, but not with analogous data of mine. I have to take a closer look at that.

**Comment by Vincent31Fr** [comment]
Tested and works perfectly! Thanks
