### ISSUE TITLE
Usability/Feature: Add cross links from Assignment and Schema Definition admin/config pages

### ISSUE THREAD

**Issue by fwolfst** [cosmocode/dokuwiki-plugin-struct#487]
Switching between the admin/config pages for schema definition and schema/namespace-assignments seems to be a common process.

In https://github.com/cosmocode/dokuwiki-plugin-struct/blob/12ce640443fbda6da53617201d6cedf4b8bb5eb3/lang/de/assignments_intro.txt#L8 a link to the other page could be added, such that it brings you to the definitions in one click.

**Comment by splitbrain** [comment]
Both pages are linked in the TOC.
