### ISSUE TITLE
have changes create revisions

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#5]
Currently struct timestamps and page revisions are out of sync. In addition when you edit struct data only without changing anything in the page's source no page revision will be saved.

The best solution would be to bring the timestamps in sync and have struct chnages force a new page revision as well.

If that turns out as not easily achieved, struct changes should create virtual entries in the changelog.

**Comment by splitbrain** [comment]
Related to this. Currently editing struct data only will not reflect this data in the output, because the page is not rerendered (as it wasn't changed)

**Comment by splitbrain** [comment]
I think to achieve this, we will need to introduce a new event in ``saveWikiText()`` and maybe refactor it a bit. To do so we need some tests first. The new event should allow to force a save in the BEFORE event even though ``$text == rawWiki($id, '')`` evaluates to true.

**Comment by splitbrain** [comment]
tests have been added. ready for refactoring and introduction of the new event.

**Comment by splitbrain** [comment]
This has now been implemented. We should write a few tests to check the entry action component, though.

**Comment by micgro42** [comment]
Diff-View is still missing, otherwise this issue should be done with the merge of #24
