### ISSUE TITLE
Lookup does'nt find Entrys after update 2020-05-14 with filter on Page-Data

### ISSUE THREAD

**Issue by saggi-dw** [cosmocode/dokuwiki-plugin-struct#501]
Hi,

after the update to 2020-05-14 a Lookup like this:

```
---- struct lookup----
schema: maintenance
filter   : system = $STRUCT.system.internal number$ 
sort: ^date 
csv: 0
----
```
does not find any Entry. Without 'filter' all Entrys are visible, but the field 'system' is empty.
'system' is a lookup to a ex-page scheme 'system', field: 'internal number',
The field is filled in the page-scheme.
SQL Test: `SELECT * FROM data_maintenance`
Result before Update:
`ns:ns1:ns2:page`
After Update:
`["",ns:ns1:ns2:page]`

Edit:
It seems that the correct data something like this is?
`["ns:ns1:ns2:page",0]`
A newly created row shows this...

Thanks for help.

**Comment by annda** [comment]
I assume the newly created data is shown correctly in your aggregation table with the filter.

Can you please post your schema configurations as JSON exported in the schema editor?

**Comment by saggi-dw** [comment]
Hi annda,

I'm sorry for the delay. 
Enclosed are the files (all lookups and the page).
I hope this will help. I have exported one Line of the "maintenance" table.
[Schema_after_Update.zip](https://github.com/cosmocode/dokuwiki-plugin-struct/files/4639955/Schema_after_Update.zip)
[Schema_before_update.zip](https://github.com/cosmocode/dokuwiki-plugin-struct/files/4639956/Schema_before_update.zip)

**Comment by annda** [comment]
Thanks for the uploads. Please reinstall the plugin. The latest version includes a migration #503 that should fix your data.

**Comment by saggi-dw** [comment]
Thank you, works perfect :)

**Comment by saggi-dw** [comment]
Hi annda,

the problem is solved for Update from DB Version 16 to 17.
Tryed on the Live Environmeent (running DB Version 15) i get some unexpected fields.
In one Lookup Field i have in DB Version 15 `35` in DB Version 17 `"[""["""",35]""`

Maybe the fix will now double run over some lookups?
V15:
```
"type","name","item no","head","zone 1","zone 2","feed","rpm","pressure","dosage","remark","short sign"
"Spritzguss","Polyethylen (LDPE)","0001K","0","0","0","0","0","0","","nicht spritzbar","35"
```
V17:
```
"pid","type","name","item no","head","zone 1","zone 2","feed","rpm","pressure","dosage","remark","short sign"
"","Spritzguss","Polyethylen (LDPE)","0001K","0","0","0","0","0","0","","nicht spritzbar","[""["""",35]"",0]"
```

Do you need more Information? I have resetted to a backup, but I can run the update again.

saggi

**Comment by annda** [comment]
This is a very weird case. I will need your whole SQLite database in version 15 to investigate further, and some details about your system: OS, PHP version, SQLite version.

Also, can you please re-do the upgrade and see if you have the same issue again?

**Comment by saggi-dw** [comment]
A re-do end in the same issue.

Dokuwiki runs on a Synology NAS. Apache server 2.2, PHP 7.0
select sqlite_version() delivers 3.10.2

I have exported the database and all schemes. Is it possible to send you a password for the files? Unfortunately some of the data inside is not public.

**Comment by splitbrain** [comment]
@saggi-dw easiest way would be to send us the `data/meta/struct.sqlite` file. You can email it directly to dokuwiki@cosmocode.de or use something like https://send.firefox.com/ to send us a link.

**Comment by annda** [comment]
I have just released another update which should fix the isssue. Please reinstall the plugin and try again.

**Comment by saggi-dw** [comment]
@splitbrain Thank you, I have sent the File.

@annda I have updated the plugin and run into several errors by SQL:
HY000 1 no such column: T5.rid:
HY000 1 no such column: data_products.rid:
Error:
`SQL execution failed for SELECT data_products.rid AS rid, data_products.pid AS PID, data_products.rev AS rev, schema_assignments.assigned AS ASSIGNED, data_products.col1 AS C0, data_products.col2 AS C1, data_products.col5 AS C2, data_products.col6 AS C3, data_products.col11 AS C4 FROM data_products AS data_products LEFT OUTER JOIN schema_assignments AS schema_assignments ON data_products.pid != '' AND data_products.pid = schema_assignments.pid AND schema_assignments.tbl = 'products' WHERE ( ( data_products.pid = '' OR ( GETACCESSLEVEL(data_products.pid) > 0 AND PAGEEXISTS(data_products.pid) = 1 AND (ASSIGNED = 1 OR ASSIGNED IS NULL) ) ) AND data_products.latest = 1 AND ( ( data_products.col7 != '' AND data_products.col7 = ? ) ) ) GROUP BY data_products.pid, data_products.rid, C0, C1, C2, C3, C4 ORDER BY CAST(data_products.col11 COLLATE NOCASE AS DECIMAL) DESC [Search.php:365]`

Many thanks for your time and sorry for the problems...

**Comment by annda** [comment]
This looks like the migrations did not run, since the first thing they do is create the `rid` columns. 

We had no problems migrating your database (I just mailed it back). Since I can't reproduce the error this time, I can't really offer any solutions (except try again or use the database migrated by us).

**Comment by saggi-dw** [comment]
Thank you all, the second try converts the database. I will have a look at the data in the next week. Now I wish a nice weekend when you also have holiday.

**Comment by saggi-dw** [comment]
Hi @annda,
the database is functional.
One issue: a multi-lookup to a page-scheme is not converted properly (from V15->V17). 
```
"pid","type","systems","supplier","no","description","comment"
"","["""",5]","[""value"",0]","["""",2]","Z00F04135","Low Shear Bolt M8x20",""
```
is what I get (also with the converted sqlite from you).

This is what I get from my test-system (dbversion V15->V16->V17):
```
"pid","type","systems","supplier","no","description","comment"
"","["""",5]","[""ns:ns1:ns2:page"",0]","["""",2]","Z00F04135","Low Shear Bolt M8x20",""
```
Table is 'spareparts'.

For me the problems are solved, I have exported the data from test to live system.
This message is only for information.

Thank you for your help!
