### ISSUE TITLE
%pageid% field behaves like %title% on PHP 5.6

### ISSUE THREAD

**Issue by Digitalin** [cosmocode/dokuwiki-plugin-struct#504]
Hi, 
Since very lasts releases of struct, with a wiki running on PHP 5.6, the %pageid% name field has the same behaviour as expected with %title%, at least begins with the first heading of template page. 
It is same for all schema pages but strangely  still not the case on a local copy that runs on PHP 7.2 (first time I notice a different behavior between the two wikis, so it could be relevant)

**Comment by annda** [comment]
It looks like this has been a problem for a long time now. The link is generated as a normal page link using all the usual mechanisms. It does not really have anything to do with PHP version. Can you compare the setting "useheading" in the configurations of your wikis? This is probably the reason why they display the `%pageid%` differently.

**Comment by Digitalin** [comment]
Yes, it was the useheading setting. Thanks.

**Comment by annda** [comment]
Reopening because the issue report is still valid and valuable, thanks @Digitalin
