### ISSUE TITLE
%lastupdate% and %lasteditor% columns are empty

### ISSUE THREAD

**Issue by asereq** [cosmocode/dokuwiki-plugin-struct#523]
I'm using the struct pugin and I interested in get the data from the remote api and know when was the last modification of each row and who did this modification (inline editing or row inserting).
I thinked the special fields '%lastupdate%' and '%lasteditor%' was a great solution, but those columns are empty, also in the wiki web page.
The database is populated from a '---- struct global ----' block and displayed in a '---- struct table ----' block.
Maybe I missing some configuration or I am no understanding the correct use of those special columns.
I also looking for the data in the sqlite db and the dump returns rows like "... VALUES('',16,0,1,...". (the lasupdate information was never saved in the db??).
Thanks in advance.

**Comment by annda** [comment]
Struct currently does not track modification details for its data. `%lastupdate%` and `%lasteditor%` are metadata of pages, managed internally by DokuWiki. So they are not available in aggregations of global data.
