### ISSUE TITLE
Updating a page does make entries of "struct serial" aggregation disappear

### ISSUE THREAD

**Issue by pippcat** [cosmocode/dokuwiki-plugin-struct#526]
I use struct serial to compose a list of agreements during meetings in the protocol wiki page. The list is there until I do a change to the page content. Once that has been done the list disappears:
![structlist](https://user-images.githubusercontent.com/19587872/95226250-ffd16c80-07fc-11eb-8db6-6856db84ec11.gif)

I had a look at the sqlite DB: there is a column called "latest" in the corresponding table of the used scheme. The value is "1" before changing the wikipage and "0" after. The table reappears once I manually set it back to "1". Is that expected behavior? If so, what's the reasoning behind it? Is there a way to keep the table entries visible?

Additional information:
Dokuwiki Release 2020-07-29 "Hogfather"
running on Debian 9 using PHP 7.0.33-0+deb9u9 (cli) (built: Aug 24 2020 11:14:22) ( NTS )
using struct plugin 2020-08-26 and sqlite plugin 2020-04-09
Scheme and database: [data.zip](https://github.com/cosmocode/dokuwiki-plugin-struct/files/5335119/data.zip)

**Comment by annda** [comment]
This seems to be a side effect of having the same schema `vereinbarungen` that you use to create your **serial data** also assigned to your **page**.  In the screencast I can see a collapsed struct form below your editor window and the page is found in the schema assignments in the database dump.

Is there a reason for this assignment? If not, please remove it to avoid the problem in the short term.

Technically, as soon as you save a new page revision with new struct data (coming from the collapsed form), all previous data rows in the `vereinbarungen` tables pointing to the same page id are seen as outdated and `latest` is set to `0`. As a result also erroneously invalidating all serial data with the same schema and page id. This of course should happen only to page data. At this point there is no check that makes this distinction, we need to implement that.

Thanks for the detailed report that helped us catch an edge case not yet covered by tests!

**Comment by pippcat** [comment]
Wow, thanks for the fast response. :heart: 
First of all, your're right, once I delete the assignment the error doesn't appear anymore. The reason for the assignment is that I want to see those entries on top of the wikipage as well as in a list of all "vereinbarungen" in all namespaces on another page and namespace. AFAIK this only works if I assign the scheme to the namespace, or do I miss something here?

**Comment by pippcat** [comment]
Once again: it there is a way to circumvent the bug and still be able to generate a list of entries of those kind in all wiki pages?

**Comment by annda** [comment]
The latest release 2020-10-14 fixes the bug.

But I don't quite understand how you combine page and serial data. I think you should be using `---- struct table ----` instead of `---- struct serial ----` to see the list of all `vereinbarungen` on any page. Serial data actually "lives" only on the page you have entered it and does not appear anywhere else.

**Comment by pippcat** [comment]
Installed it and it works. Great, thank you!

I try once again to explain:
- we use struct serial to accumulate agreements in meeting protocols as well as in other pages in other namespaces
- there is a wikipage in a seperate namespace where a list of all agreements of all wiki pages is compiled automatically with a struct table using this "vereinbarungen" scheme 
- if I don't assign the scheme to the wiki pages which have those struct serial agreement lists the struct table on the page with the list of all agreements doesn't display anything
I don't see any other way to compile this list!?

**Comment by GJRobert** [comment]
> The latest release 2020-10-14 fixes the bug.

Just a fix I need today! Thank you so much!

> 
> But I don't quite understand how you combine page and serial data. I think you should be using `---- struct table ----` instead of `---- struct serial ----` to see the list of all `vereinbarungen` on any page. Serial data actually "lives" only on the page you have entered it and does not appear anywhere else.

For me (may not be the same for @pippcat), I have assigned a schema to a namespace so that every page can hold one record. But there are times that certain pages within may need to hold more than one records, and these are added per page. So a serial editor to coexist with the page data already there without being overwritten by page edits is really feasible.

**Comment by annda** [comment]
Fixed in 9e5ba3244003a377d4862139d60bf2280278dd70

Thank you both for clarifying the use case.
