### ISSUE TITLE
[Q] Why does struct.sqlite seem to be touched just because of user viewing wiki pages?

### ISSUE THREAD

**Issue by GJRobert** [cosmocode/dokuwiki-plugin-struct#528]
Hi,
I have my main DW installation kept both on my laptop (via localhost served by MAMP), and on my NAS (network-attached storage) server, and there is an app provided by the NAS to sync between the two sides like Dropbox is doing. The only viewer of the wiki on the laptop is me, but with the NAS Web server there are dozens of viewers to my DW site.

It is with this set-up did I found that `struct.sqlite` seems to get touched very frequently, because whenever the file is changed (theoretically) it gets uploaded/downloaded via my sync daemon, but my edits are not many, and a struct.sqlite is generated even with no schema created, and my sync daemon often notifies me that this or that struct.sqlite (I have some DW animals) is uploaded or downloaded.

So this is an ABC question: what is the mechanism between struct.sqlite and the activities of the users of the DW?

The problem I want to avoid is the sync conflict between my two copies of DW. (In fact conflicts do happen now and then, and recently with my edits to the schemas increase, sometimes the data get corrupted). I can limite my edits solely via one side, but I wonder if struct.sqlite can also get modified just because the viewing activities of Web guests, then I may encounter big problems when my databases get bigger and they will be exposed to untimely sync conflicts and corruptions.

Please correct me if any of my speculations is wrong.

**Comment by GJRobert** [comment]
Or, simpler, can anyone confirm for me that does struct plugin has to write to struct.sqlite all the time?
Why? Because it relies on meta data of wiki pages? But how come only "viewing by guests" can trigger database writes?
Is this mandatory?

**Comment by annda** [comment]
This looks like a bug to me. You are absolutely right, struct sometimes writes to the database when no data has been changed. Specifically, it updates its own page info when metadata is being rendered (basically every time a page is served not from internal cache). It's an update, so the database does not grow. But IMO this should not be happenning. We should check if a write is necessary.

I will look into that.

**Comment by GJRobert** [comment]
Please have my bow of gratitude
![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Japan_-_Tokyo_%289980668875%29.jpg/320px-Japan_-_Tokyo_%289980668875%29.jpg)
([Maya-Anaïs Y.](https://www.flickr.com/photos/54238729@N07/9980668875), [CC-BY 2.0](https://creativecommons.org/licenses/by/2.0/))
