### ISSUE TITLE
Submitting schema assignments goes to start page and doesn't work

### ISSUE THREAD

**Issue by jf908** [cosmocode/dokuwiki-plugin-struct#531]
If I attempt to create a schema assignment for any schema with any page/namespace pattern, I will be navigated to the start page but no changes will be made. No errors appear and only deprecation warnings appear in devel.log with logging turned on.

I am using XAMPP and have tried two PHP versions 7.3.24 and 7.4.12 but the issue still persists.

**Comment by jf908** [comment]
This issue led me on a long bug hunting goose chase and in the end it was just because of a missing tag haha. I guess there are not many people who use this plugin with the vector theme which doesn't use a `<form>` element for its search bar which breaks the form. I kinda wish Dev Tools would tell you about this kind of thing because the inspector shows the "fixed" version of the DOM.

**Comment by splitbrain** [comment]
thanks for the report and the fix!
