### ISSUE TITLE
Import pages from CSV only works if rows are sorted alphabetically

### ISSUE THREAD

**Issue by Sebastian-dm** [cosmocode/dokuwiki-plugin-struct#536]
When I import data from CSV it will only work if I sort all rows by "pid" alphabetically.
This is not a major issue but it was very frustrating not knowing it is required.

I hope you can add it to the page detailing import.

**Comment by annda** [comment]
I can't reproduce this behavior.

If the problem still persists, please provide more details about the versions of DokuWiki and struct, about your data and which data type you are importing.
