### ISSUE TITLE
BUG: Aggregation trailing zeros are stripped from the decimals even trimzeros is false

### ISSUE THREAD

**Issue by LMS235** [cosmocode/dokuwiki-plugin-struct#539]
In Aggregation the leading zeros are cut off although the parameter "trimzeros" is set to false.

The leading zeros are present in data processing and export.

However, these should also be displayed in the aggregations.

**Comment by annda** [comment]
Do you mean leading or trailing zeros? Trailing zeros are handled properly.

Can you give us more specifics? Like the exact decimals, and the processing and export workflows that work according to your expectations? Please post the input and output values.

**Comment by LMS235** [comment]
I want the 0's to be displayed in the aggregations.

Current:
- Value 01
- Display in the aggregations: 1

Target:
- Value 01
- Display in the aggregations: 01

Screenshot aggregations:
![image](https://user-images.githubusercontent.com/8693550/106105477-59f79400-6144-11eb-9e65-1232ceb17e27.png)


Screenshot data:
![image](https://user-images.githubusercontent.com/8693550/106105513-67148300-6144-11eb-93b2-b58952d0318b.png)

The leading 0 should ALWAYS be displayed.

**Comment by annda** [comment]
The leading zeros are stripped by PHP's [number_format()](https://www.php.net/manual/en/function.number-format.php) function, on which all the formatting options are based.

The [struct documentation](https://www.dokuwiki.org/plugin:struct:type_decimal) also explicitly says that `trimzeros` is applied to trailing zeros only, so the observed behavior is not actually a bug. If you require the leading zeros, consider switching to the text type.
