### ISSUE TITLE
All my struct databases are giving "HY000 1 no such column: data_intranet.rid:"

### ISSUE THREAD

**Issue by chrisisbd** [cosmocode/dokuwiki-plugin-struct#556]
I don't quite know when this started but all my struct data is now reporting this error and writing big red error messages all over the page.  Obviously the 'intranet' bit changes on different struct databases but the error is everywhere.

I've updated to the latest versions of all the relevant Dokuwiki plugins.

Is this a known issue or have I got something specifically broken on my system?

**Comment by chrisisbd** [comment]
Ah, a bit of searching has found this discussion:-

https://forum.dokuwiki.org/d/18182-struct-solved-error-message-hy000-1-no-such-column

I guess this must be what has bitten me

**Comment by chrisisbd** [comment]
Hmm, I've read the thread above and I'm no better off really.  I'm sure I wasn't getting this error back in August last year.

Can I fix the mess 'manually'?  I'm fairly database proficient and can can write SQL queries if necessary.  

Could someone outline what the changes to the struct and sqlite plugins are and tell me thus what needs doing.  I only have seven quite small struct databases and I'm the only user so I can just stop all access while I fix things.

**Comment by annda** [comment]
The only manual fix is the one described by andi in the forum thread:

1. update sqlite plugin first
2. set back `dbversion` in struct database to 15
3. open a page in wiki so that the migration is executed again

The last migrations (starting with 16) are impossible to do in SQL only.

This is a very weird problem, practically impossible to reproduce. See also #499

**Comment by annda** [comment]
@chrisisbd  BTW what do you mean you have seven struct databases? Or do you mean seven SQLite databases, **one** of them being `struct.sqlite3`? Or do those dbs belong to different plugins? Can you post their names here?

**Comment by chrisisbd** [comment]
Ah, oops, I have seven struct tables with corresponding table names in the (one) sqlite database of course.

How/where does one set dbversion?

**Comment by annda** [comment]
Take a look here https://github.com/cosmocode/dokuwiki-plugin-struct/issues/499#issuecomment-628724329

**Comment by chrisisbd** [comment]
Brilliant, thank you.

**Comment by chrisisbd** [comment]
... and even better, my Dokuwiki is now all back working.  Just that setting the dbversion back has made everything come right.

Thank you Anna
