### ISSUE TITLE
After update Filter reset does not work 

### ISSUE THREAD

**Issue by dranjor** [cosmocode/dokuwiki-plugin-struct#563]
I use the cloud to filter table entries. Since the last update (17.3.2021) I notice that resetting the filter has no effect. The same is when reloading the page. `?pruge=true` resets the filter as espected.

![preview](https://cloud.pingupod.de/s/NMLXey3Pw3WgCxM/preview)

**Comment by annda** [comment]
The latest release 2021-04-08 should fix the problem.

**Comment by fschrempf** [comment]
I have the same issue and I can confirm that ca94dee68f16be1342378e06e5c73981720b438f seems to fix it. Thanks!
