### ISSUE TITLE
API field

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#57]
The idea is to be able to create fields that can not be edited manually, but instead pull data from a remote API. This needs some flexible configuration and probably some kind of custom code somewhere. In addition the data needs to be pulled in periodically (via indexer cronjob).

Questions

- how to implement the custom code?
  - just some place to put classes within the plugin directory?
  - proper new plugins registering to struct plugin specific hooks?
- what kind of input would this custom code need?
  - the field configuration of course
  - the page id?
  - all the structured data already saved for the page?

The more I think about this the more I think this is not a good idea and it would be implemented better through additional custom plugins simply calling a struct helper plugin or interaracting through an API as suggested in #56

**Comment by splitbrain** [comment]
@detman thoughts? I would als need an actual use case description for such a field and the API. What data would be pulled exactly from where?

**Comment by stvoigt** [comment]
we thought of an example as documented in https://wiki.sprintdoc.de/internes:handbuchbsp:projektkpi

**Comment by splitbrain** [comment]
I just talked with @micgro42 about this and we see multiple problems with this

* the data you want to pull is attached to a certain point in time (we're unsure this is even possible with the Jira API)
* the data depends on values outside the knowledge of the type (it has to to know the sprint date, entered in a completely different field). This could be mitigated by having inputs for the type to add additional configuration data
* the type would be very specific and not very useful beyond the sprintdoc use case (eg to non-jira users) thus a separate plugin would be preferable
* the actual use case you linked to is seeing JIRA project metrics over time/sprints. This isn't really a wiki task but should ideally be covered by JIRA's reporting functions

If you insist of implementing the functionality, we'd recommend to implement it in a different specific JIRA Metrics API Plugin that simply stores it's data to the struct database through either a helper component or the remote API suggested in #56

**Comment by splitbrain** [comment]
postponed for now
