### ISSUE TITLE
Struct schema editor doesn't follow DW template style setting

### ISSUE THREAD

**Issue by vic-t** [cosmocode/dokuwiki-plugin-struct#572]
I use DokuWiki with the regular DokuWiki template. However, I changed the template style settings to create some sort of dark theme. Basically, all backgrounds are set to a dark color while all text is set to a light color. 

When trying to create a new schema with the struct plugin, I can't see the content of the configuration column because the text used there is not following my style settings, it's just black. On a dark background, that's not legible, of course.

**Comment by vic-t** [comment]
After having done a bit more research on this, it seems the problem is the following css configuration in the file  ? 
`jsoneditor.min.css`: 

```
.jsoneditor-schema-error, div.jsoneditor td, div.jsoneditor textarea, div.jsoneditor th,
div.jsoneditor-field, div.jsoneditor-value {
    font-family: droid sans mono,consolas,monospace,courier new,courier,sans-serif;
    font-size: 10pt;
    color: #1A1A1A;
}
```

The color is not taken from any template setting but set here specifically. 

Now, I wanted to overwrite this setting by putting into my `userstyle.css` like this (attribution to [MrReSc ](https://github.com/MrReSc/MindTheDark/issues/11)for the tip). 

```
.jsoneditor-schema-error, div.jsoneditor td, div.jsoneditor textarea, div.jsoneditor th, div.jsoneditor-field, div.jsoneditor-value {
    colour: var(--text);
}
```

To my surprise, this has no effect whatsoever. I had to edit jsoneditor.min.css directly which solved my issue but I'll have to repeat the measure each time struct will get an update. 

Do you have an idea why the setting in `userstyle.css` is ignored?

**Comment by annda** [comment]
If you look at the HTML of the page, you will see that CSS of the schema editor is not loaded "normally" but further down the HTML via `<link href="/lib/plugins/struct/jsoneditor/jsoneditor.min.css" rel="stylesheet" type="text/css">`. So `userstyle.css` is loaded earlier, in the sequence described in [the documentation](https://www.dokuwiki.org/devel:css#dokuwiki_stylesheets).

This was a conscious decision by the developers, who decided not to include the rarely used styles for every page view.

Of course you can always override any styles in your userstyles using the maligned `!important` keyword.
