### ISSUE TITLE
Filtering: Seemingly no possibility to make a negative match for multiple values

### ISSUE THREAD

**Issue by vic-t** [cosmocode/dokuwiki-plugin-struct#581]
Say I have a text field "color" with the entries "yellow", "green", "red", "blue". Now I wish to see all entries where the color is either "yellow" or "green". The plugin filter offers multiple ways of doing that.

Using filteror: 

```
filter: color = yellow
filteror: color = green
```

Using regex: 

`filter: color =* yellow|green`

Using IN: 

`filter: color IN ("yellow", "green")`

Now, instead, I'm trying to do the opposite, to **_not_** show the entries where the color is either yellow or green. Please do correct me if I'm wrong but that does not seem to be supported by the struct plugin. 

Filteror does not work: 

```
filter: color <> yellow
filteror: color <> green
```

That makes sense since you'd have to combine the two using an AND statement instead of OR to get the wanted result.

Unfortunately, NOT IN doesn't seem to exist or is being ignored: 

`filter: color NOT IN ("yellow", "green")`

It would be great if you could add NOT IN as an option. In addition or as an alternative, please make "filterand" available as that would work with multiple negative matches.

**Comment by saggi-dw** [comment]
Hi,
Why not just 'filterand'?
That works:

```
---- struct table ----
schema: colors
cols: *
filter: color <> yellow
filter: color <> green
csv: 0
---- 
```

saggi

**Comment by vic-t** [comment]
Hi saggi, 

Thanks for the tip! It wasn't clear to me from the documentation that it's possible to use multiple filter instructions. 

Plugin page owners: What do you think about creating one more section called "multiple filters" where you demonstrate this possibility? I guess saggi's example would do just well.

**Comment by vic-t** [comment]
Having said that, since IN is supported, it would still be nice if NOT IN could also be supported.

**Comment by splitbrain** [comment]
> Plugin page owners:

It's a wiki. There are no owners. If you can improve the documentation, go ahead and do it.

**Comment by vic-t** [comment]
Hi Andi, I thought I read at some point somewhere that changes by the public are no longer accepted. If that's not the case, happy to add this to the documentation myself.

**Comment by vic-t** [comment]
Added the section "multiple filters" to the documentation, see https://www.dokuwiki.org/plugin:struct:filters#multiple_filters. Hope it will be of help to new users.

**Comment by annda** [comment]
Working and documented.

**Comment by Chris75forumname** [comment]
> @saggi-dw
> Hi, Why not just 'filterand'?

Because it also removes all rows with empty fields from the set of results.
