### ISSUE TITLE
Having control where to display struct data on page

### ISSUE THREAD

**Issue by christo-ph** [cosmocode/dokuwiki-plugin-struct#591]
Currently, as far as I can tell,  its only possible to show the struct data of a page at the top or bottom of a page.

I need more control. Is there a way to display the struct data via placeholder like `{{structheader}}` or similar?

Thank you!

**Comment by Juergen-aus-Zuendorf** [comment]
My workaround at this point is to only show the struct data in the editor (and NOT on the page). Then I create an aggregation at a suitable place on the page where the hidden values are listed.

**Comment by annda** [comment]
I think the solution proposed by @Juergen-aus-Zuendorf accomplishes the goal. In the schema editor, just disable displaying all the fields **on the page** using the `visibility.inpage` setting: https://www.dokuwiki.org/plugin:struct:type
