### ISSUE TITLE
Autocomplete user in LDAP throws: The user backend can not search for users User.php:66

### ISSUE THREAD

**Issue by rblaszcz** [cosmocode/dokuwiki-plugin-struct#592]
Some backends do not and sometimes should not lookup all users (like ldap).
By default struct throws exception on every keypress _The user backend can not search for users User.php:66_
If the backend does not support it I believe autocomplete should not work and this is ok.

So my workaround is in `struct/types/User.php`:
`if (!$auth->canDo('getUsers')) return array();`

**Comment by annda** [comment]
Fixed in 5827d73
