### ISSUE TITLE
Feature request: multiple namespace search in autocomplete

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#593]
At the moment, it looks as though the autocomplete configuration for the Page type can take a single namespace to search in. I have people in one namespace, and groups in another, and I'd like to be able to have a link to either in a Struct field. At the moment, I can only do this by having Struct search the whole site.

I'd like to be able to give the namespace option as `:people, :groups`, or some other way of specifying search in multiple namespaces.

**Comment by annda** [comment]
I'm not sure that this is currently possible. Autocompletion uses the core method `_ft_pageLookup()` internally, which seems to accept only one namespace parameter. @splitbrain Am I overlooking something?

**Comment by splitbrain** [comment]
You're right. I missed that the namespace is added as an `@parameter`, I thought it's different.

So I see two ways to implement this:

1. run the ft_pageSearch() call multiple times for each namespace, then merge the results
2. run the ft_pageSearch() call without a namespace, then filter the results

I think 2 is the more performant approach

**Comment by annda** [comment]
The `namespace` option has been migrated to a more flexible `filter` (together with `postfix`).

Filter is a regular expression, written without the delimiter '/' for backwards compatibility. There is no need to migrate any configs manually.

You can write arbitrary regular expressions in the autocomplete filter, e.g. `(namespace1|namespace2:subnamespace|:topnamespace)` for multiple namespaces.
