### ISSUE TITLE
Request: Raw data mode

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#594]
At present the struct aggregations always try to render the full syntax of the values they get from the database - for instance, a URL value is rendered with its `<a href`... around it. I'd like to be able to use the value aggregation in particular to emit the raw value that's stored in the database.

**Comment by iainhallam** [comment]
I think to do this would mean adding a flag to all the types in struct to enable them to emit raw values, and a syntax for the user to request this - perhaps for the table and list:

```
raw: 1
```

And for value:

```
{{$schema.field ? raw}}
```

I don't see an easy way offhand of adding this only to the value aggregation, as it just works with what it's passed by the types.

**Comment by splitbrain** [comment]
I would like to keep things "simple". I know struct isn't, but adding additional output modes makes everything more complex.
