### ISSUE TITLE
Documentation: What schema names are valid?

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#595]
I tried starting a schema name with a capital letter, which was silently changed to lowercase, and that got me wondering what the restrictions are on schema names? What are the valid characters? Can they start with a number?

**Comment by splitbrain** [comment]
See https://github.com/cosmocode/dokuwiki-plugin-struct/blob/848c3698152cc99bc3855accd8658bfcda781768/meta/Schema.php#L160-L167

Feel free to update the docs accordingly.
