### ISSUE TITLE
unable to install plugin

### ISSUE THREAD

**Issue by tomasvelehradsky** [cosmocode/dokuwiki-plugin-struct#606]
after installation a got:

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /volume2/web/edu/lib/plugins/struct/action/output.php on line 23

Please, can you help me?

**Comment by runout-at** [comment]
this sounds like a problem with your php version, which might be too old.

if you have to stick to the old php, you could try to remove the `protected` from the constants declarations in several parts of the code.
