### ISSUE TITLE
Unable to build link to wiki page based on columns

### ISSUE THREAD

**Issue by jeffchulg** [cosmocode/dokuwiki-plugin-struct#607]
hi,

is there any capability (existing or planned for implentation) which would allow to create a link to page in wiki based on the value of a column.

For instance: if struct contains a table "fruits" with a value "apple" and the wiki has a page in a given namespace (let's say fruits) with the name "apple", create an URL `[[fruits:apple]]` that points to former page.

**Comment by annda** [comment]
This is not possible in struct tables / aggregations. But something similar can be accomplished with the [structautolink](https://www.dokuwiki.org/plugin:structautolink) plugin.
