### ISSUE TITLE
Unable to perform a "DISTINCT" query on a column

### ISSUE THREAD

**Issue by jeffchulg** [cosmocode/dokuwiki-plugin-struct#608]
I would like to be able to do a behavior like 

`SELECT DISTINCT <column_value> FROM <struct_table>`

in order to have just the column values once.

Is it possible ?

**Comment by splitbrain** [comment]
Please provide the syntax you're currently using, the results you get and what you would like to have changed about it.

**Comment by jeffchulg** [comment]
Hi,

unfortunalty, more than one year later, I abandonned the idea.

The point was, I think : 

a struct table with at least a field "Application" and a field "environment"

Data could then have the same application in different environments

I wanted to list out values of application field no matter the environment.

**Comment by annda** [comment]
This is currently not supported.
