### ISSUE TITLE
querying a value is not working

### ISSUE THREAD

**Issue by Nif9** [cosmocode/dokuwiki-plugin-struct#610]
Hello,
I'm trying to use the struct ability to get a single value from a schema as mentionned in the documentation. Following syntax guidelines, I input in a wiki page this code:

`{{$qms_model.Responsible? filter: "Code = VDD"}}`

I'm expecting to get the Responsible of a template called VDD but I get back a no data found message. The schema is a serial one, already used in other pages with struct table format without any issue.
Am I wrong in the syntax? or is there any tip? or a bug...

Thank you for any feedback.

**Comment by iainhallam** [comment]
Have you tried with a space before the question mark? If that works, this becomes a bug about making the inline syntax parser more forgiving!

**Comment by Nif9** [comment]
I've been able to get access to debug.log and I get numerous "deprecated" messages. From plugins bureaucracy, struct and bootstrap.
Here's an extract:

`
09:37:29 : utf8_strtoupper() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in /var/www/dokuwiki/lib/plugins/bureaucracy/syntax.php:32 dokuwiki\Utf8\PhpString::strtoupper() should be used instead!
09:37:29 : require_once() is deprecated. It was called from require() in /var/www/dokuwiki/inc/load.php:147 Autoloading. Do not require() files yourself. should be used instead!
09:37:29 : trigger_event() is deprecated. It was called from dokuwiki\plugin\struct\meta\Column::allTypes() in /var/www/dokuwiki/lib/plugins/struct/meta/Schema.php:110 \dokuwiki\Extension\Event::createAndTrigger should be used instead!
09:37:29 : utf8_strtolower() is deprecated. It was called from dokuwiki\plugin\struct\meta\Schema::findColumn() in /var/www/dokuwiki/lib/plugins/struct/meta/Search.php:672 dokuwiki\Utf8\PhpString::strtolower() should be used instead!
[...]
09:37:29 : Doku_Handler::_addCall() is deprecated. It was called from syntax_plugin_bootswrapper_bootstrap::handle() in /var/www/dokuwiki/inc/parser/handler.php:279 addCall should be used instead!
`
I don't know if it's "only" warnings or errors.

**Comment by Nif9** [comment]
Hi! 
I'm so happy to found a solution :) (a workaround) and it comes from you @iainhallam :)

I've installed the Struct template plugin, and with a query giving back a single record, I managed to get my single value!

I've used these 2 syntaxes in my page:
`
**Single Value: responsible of model coded STR**
{{$qms_model.Responsible? filter: "Code=STR"}}
\\

**Struct template responsible of template coded STR**: 
<struct-template>
---- data ----
schema: qms_model
cols: Responsible,Code
filter: Code=STR
----
{{$$qms_model.Responsible}}
</struct-template>`

Only the second provided the expected value ("no data found" for the single value)...
Please, let me know if you acknowledge that this is a bug from Struct Single value (workaroundable with structtemplate wich is very useful! Thank you @iainhallam !

**Comment by annda** [comment]
The difference between the two examples is that `{{$qms_model.Responsible? filter: "Code=STR"}}` fetches data from the **current page only** as specified in the [https://www.dokuwiki.org/plugin:struct:aggregation:value](documentation).

structtemplate fetches **all data** from the schema and then filters it. 

@Nif9 It seems you have been trying to get data from other pages with the inline syntax, which will not work. Great that you have found the structtemplate plugin by @iainhallam. Your direct comparison illustrates the difference and so can be very useful for others trying to achieve the same goal.
