### ISSUE TITLE
[FR] Struct Cloud - showCount

### ISSUE THREAD

**Issue by LMS235** [cosmocode/dokuwiki-plugin-struct#613]
Hello,

in the normal Cloud Plugin (https://www.dokuwiki.org/plugin:cloud) you can use `[showCount]` but not in the Struct Cloud (https://www.dokuwiki.org/plugin:struct:cloud). 

Is it possible to implement this feature?

Regards

**Comment by LMS235** [comment]
Dokuwiki Forum - https://forum.dokuwiki.org/d/20365-struct-cloud-showcount

**Comment by annda** [comment]
Count is now displayed when summarize option is set, as has been [documented](https://www.dokuwiki.org/plugin:struct:cloud) (but maybe lost along the way).

This work with fields rendered as text, not media or color.
