### ISSUE TITLE
Cannot combine schemas in aggregation table

### ISSUE THREAD

**Issue by armandostyl** [cosmocode/dokuwiki-plugin-struct#614]
Apologies if I'm being stupid and not realizing how it should work.

I can't have an aggregation table with two different schemas (with some similar fields, others different). When I set it up, I get "No Results Found". I have tested this and it happens when one of the two schemas has no data in the field which will be shown in one of the table's columns (but might also happen even if there are entries, not sure yet).

**Comment by annda** [comment]
Combining schemas only works when they are assigned to the same pages, because they are internally joined on the page id.

Do you have the same assignments for both of your schemas?
