### ISSUE TITLE
Change SQLite ORDER BY by config

### ISSUE THREAD

**Issue by mschlenstedt** [cosmocode/dokuwiki-plugin-struct#616]
It would be great if one could change the SQLite sorting behaviour by config or (better) option in the aggregation tables. For example I need case insentive sorting in some aggregations. Currently as far as I could seen I only can choose bewteen ASC and DESC, but no more options. Solution for my problem is described here: https://michaelsoolee.com/case-insensitive-sorting-sqlite/

As far as I could seen sorting is done somewhere here:

https://github.com/cosmocode/dokuwiki-plugin-struct/blob/bbfcbfb5a517c054710ae343fdd473359a3e61a9/meta/QueryBuilder.php#L239

Maybe one could add here some more options SQLite offers by default.

**Comment by splitbrain** [comment]
I would argue that non-casesensitive sorting would *always* be the better option. So maybe we simply add the NOCASE collation always.

**Comment by annda** [comment]
Sorting has been case-insensitive for years now (eb55dc17).

@aplitbrain Do we want to introduce any search configuration options, as requested by the original reporter?

**Comment by splitbrain** [comment]
not needed.

**Comment by annda** [comment]
Thanks for the details. In this special case, namely sorting by the "magic" column `%title%`, the collation is not yet applied.

I need to find the best way to apply it consistently.
