### ISSUE TITLE
Restrict depth of autocomplete search for Page type

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#622]
I have some pages with their own subpages that shouldn't appear in the output of autocomplete, so I would like to be able to specify that the search has a maximum depth. I can imagine that other situations might warrant a minimum depth - this would allow searching multiple namespaces but not returning the namespace pages themselves for instance, so taking a cue from Unix find, both `autocomplete.maxdepth` and `autocomplete.mindepth` would be helpful configuration.

**Comment by annda** [comment]
The `namespace` option has been migrated to a more flexible `filter` (together with `postfix`).

Filter is a regular expression, written without the delimiter '/' for backwards compatibility. There is no need to migrate any configs manually.

You can now define depth by writing a regular expression in the autocomplete filter, e.g. `^:systems:[^:]+:components:([^:]+:){1,2}[^:]+$` will match two levels inside `components`.
