### ISSUE TITLE
How to track history of serial struct data?

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#623]
As stated [here](https://github.com/cosmocode/dokuwiki-plugin-struct/issues/178#issuecomment-248880964), "Changes to struct data should be tracked in the revisions history of a page." When I checked I noticed, that changes to serial struct data do not invoke any revision records of that page. In the [plugin manual](https://www.dokuwiki.org/plugin:struct:dbinternals) it is stated that rev (revision id of the page) is logged in the database. But, how is that helping with recovery of historical struct data?
If I go to an ancient historical revision of my page (hosting serial struct data), the table is filled with just the recent struct content, not any historical data.

**Comment by splitbrain** [comment]
serial data does not track any history

**Comment by Chris75forumname** [comment]
Okay, thank you very much! That was the answer I was looking for. BTW, THANK YOU SO MUCH FOR ALL YOUR MAGNIFICENT WORK AND CARE!

**Comment by Chris75forumname** [comment]
So am I right, this is the advantage of the data plugin over the struct plugin, that history of "serial" data can be recovered and diffs can be viewed?

**Comment by splitbrain** [comment]
1. there is no such thing as serial data in the data plugin
2. sure

**Comment by Chris75forumname** [comment]
Alright! Thanx! :-)
