### ISSUE TITLE
flt / srt action - when using dynfilters or sort, after pressing Enter, view jumps to top of the page (out of view)

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#629]
When typing a filter word into the dynfilters input form fields (below the column headers) and when using the built-in sort function of the column headers, after hitting Enter (respectively mouse click), no scroll-into-view follows! Instead after pressing Enter (respectively mouse click), view jumps to top of the page and, thus, out of view! (I tested this on a fresh install.)
I wrote some little javascript to solve this problem for me (put following code into /conf/userscript.js):

>       setTimeout(function() {
>          $my_URL = window.location;
>          $my_actions = String($my_URL).split("&")[1]; 
>          $my_actions_check = $my_actions.substr(0, 3);
>          if ($my_actions_check == 'flt' || $my_actions_check == 'srt') {
>             var $scroll_target = "div.structaggregationeditor";
>             $scroll_target = document.querySelectorAll($scroll_target)[0];
>             $scroll_target.scrollIntoView();
>          }
>       }, 300);

However, this only works on one table per page. In my case: the structaggregationeditor. You can put any other element (selector) into var $scroll_target, wherever you wish the page to scroll upon sorting/filtering.

**Comment by splitbrain** [comment]
Should be fixed by adding a unique ID to each aggregation, then a `#hash` could be added to the filter links, so that the browser scrolls to the correct location on page load.
