### ISSUE TITLE
struct type url - prefix and postfix do not work as expected

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#630]
In struct type url - prefix and postfix do not work as expected: 
- Expected behaviour: prefix and postfix like in struct type text are placed before and after the actual entry, respecively.
- Actual behaviour: prefix and postfix are build into the link like so: https://prefixwww.test.depostfix
- Problem: This is neighter intuitive nor useful. 
- Solution: However, please provide additional prefix and postfix fields for before and after actual entry (needed for aggregationlist).

**Comment by saggi-dw** [comment]
The behavior is in line with what is expected:

```
autoscheme: https
prefix: www.dokuwiki.org/start?do=search&q=
postfix: &id=dokuwiki
```
`value: struct`
results in:
`https://` `www.dokuwiki.org/start?do=search&q=` `struct` `&id=dokuwiki`

Or have I misunderstood that?

**Comment by Chris75forumname** [comment]
Alright! However, please provide additional prefix and postfix fields for before and after actual entry (needed for aggregationlist).
