### ISSUE TITLE
Latest update breaks my wiki

### ISSUE THREAD

**Issue by chrisisbd** [cosmocode/dokuwiki-plugin-struct#632]
I am running the latest dokuwiki and just updated the struct plugin to the version released yesterday
and it broke all my struct plugin usage with errors like the
following:-

2023-03-14 14:36:36     /home/chris/wiki/lib/plugins/sqlite/classes/adapter_pdosqlite.php(100)  PDOException:
SQLSTATE[HY000]: General error: 1 no such column: data_hebergements.published
  #0 /home/chris/wiki/lib/plugins/sqlite/classes/adapter_pdosqlite.php(100): PDO->query()
  #1 /home/chris/wiki/lib/plugins/sqlite/classes/adapter.php(161):
helper_plugin_sqlite_adapter_pdosqlite->executeQuery()
  #2 /home/chris/wiki/lib/plugins/sqlite/helper.php(558): helper_plugin_sqlite_adapter->query()
  #3 /home/chris/wiki/lib/plugins/struct/meta/Search.php(384): helper_plugin_sqlite->query()
  #4 /home/chris/wiki/lib/plugins/struct/meta/AggregationTable.php(86): dokuwiki\plugin\struct\meta\Search->execute()
  #5 /home/chris/wiki/lib/plugins/struct/syntax/table.php(114):
dokuwiki\plugin\struct\meta\AggregationTable->__construct()
  #6 /home/chris/wiki/inc/parser/renderer.php(117): syntax_plugin_struct_table->render()
  #7 /home/chris/wiki/inc/parserutils.php(525): Doku_Renderer->plugin()
  #8 /home/chris/wiki/inc/parserutils.php(289): p_render_metadata()
  #9 /home/chris/wiki/inc/common.php(246): p_get_metadata()
  #10 /home/chris/wiki/doku.php(97): pageinfo()
  #11 {main}

Reverting to the previous version of struct has fixed the errors.

**Comment by chrisisbd** [comment]
It may not be the latest change that has broken my wiki, the version I am using that works is as follows:-

base   struct
author Andreas Gohr, Michael Große, Anna Dabrowska
email  dokuwiki@cosmocode.de
date   2022-08-26
name   struct plugin
desc   Add and query additional structured page data
url    https://www.dokuwiki.org/plugin:struct

**Comment by saggi-dw** [comment]
I think it is the same as in #556.
Set the db version to 18, current is 19.

**Comment by chrisisbd** [comment]
Ah, yes, that's probably it, thank you.

Would this have been caused by missing out a couple of updates of the plugin?

**Comment by saggi-dw** [comment]
The reset of the db-version is only neccesary when the update is not done properly. Only if you get the error "HY000-1".
https://forum.dokuwiki.org/d/20832-after-update-editor-shows-hy000-1-no-such-column-data-providerpublished/3

**Comment by annda** [comment]
I see more of those DB update error reports. However, I still cannot reproduce the behavior, so I don't know what causes it and how to fix it. A new version of the sqlite plugin is in the works, which will hopefully make those weird errors disappear.
