### ISSUE TITLE
version information

### ISSUE THREAD

**Issue by glensc** [cosmocode/dokuwiki-plugin-struct#635]
the wiki page says php 5.6 is required:
- https://www.dokuwiki.org/plugin:struct#installation
> :!: Please also note that this plugin requires PHP 5.6 or higher.

but in reality, it doesn't run on PHP 5.6:
```
[Mon Mar 27 10:47:09.414207 2023] [:error] [pid 14] [client 172.21.0.1:59766] PHP Parse error:  syntax error, unexpected '?' in /usr/share/dokuwiki/lib/plugins/struct/action/bureaucracy.php on line 114
```

- https://github.com/cosmocode/dokuwiki-plugin-struct/blob/709b802596d9b040d121d72ee25f6575659d47b8/action/bureaucracy.php#L114

**Comment by glensc** [comment]
null coalesce operator seems php 7.0 feature:

- https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by glensc** [comment]
also, dokuwiki version specified is incorrect, wiki says 2018-04-22 "Greebo"  compatible, but I get this error:

```
[Mon Mar 27 11:15:27.844899 2023] [php7:error] [pid 17] [client 172.21.0.1:46594] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\Extension\\Event' not found in /usr/share/dokuwiki/lib/plugins/struct/helper/db.php:69
Stack trace:
#0 /usr/share/dokuwiki/lib/plugins/struct/helper/db.php(23): helper_plugin_struct_db->init()
#1 /usr/share/dokuwiki/inc/plugincontroller.class.php(109): helper_plugin_struct_db->__construct()
#2 /usr/share/dokuwiki/inc/pluginutils.php(45): Doku_Plugin_Controller->load('helper', 'struct_db', false, false)
#3 /usr/share/dokuwiki/lib/plugins/struct/meta/PageMeta.php(21): plugin_load('helper', 'struct_db')
#4 /usr/share/dokuwiki/lib/plugins/struct/action/title.php(42): dokuwiki\\plugin\\struct\\meta\\PageMeta->__construct('start')
#5 /usr/share/dokuwiki/inc/events.php(229): action_plugin_struct_title->handleMeta(Object(Doku_Event), NULL)
#6 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')
#7 /usr/share/dokuwiki/inc/parserutils.php(502): Doku_Event->advise_after()
#8 /usr/share/dokuwiki/inc/parserutils.php(272): p_render_metadata('start in /usr/share/dokuwiki/lib/plugins/struct/helper/db.php on line 69
```

Event class was added in:
- https://github.com/dokuwiki/dokuwiki/commit/e1d9dcc8b460b6f029ac9c8d5d3b8d23b6e73402

which appears in 2020-07-29 release (Hogfather)

**Comment by splitbrain** [comment]
Please feel free to update the docs accordingly.

**Comment by glensc** [comment]
@splitbrain and what are the versions required?

**Comment by splitbrain** [comment]
Well, from what you write I assume at least PHP 7.0 and Hogfather?
