### ISSUE TITLE
The "decpoint" parameter in decimals is not shown in struct_inlineditor, appropriately

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#636]
The "decpoint" parameter is documented as: "The character to use as a decimal point in output." Hence, I would expect the value in the "struct_inlineditor" to be shown to the user with "decpoint" in place, instead of decimal dot, which it actually does.

**Comment by annda** [comment]
"Output" means aggregations, lists and struct banners. The editor displays the value as it is internally stored. In the case of decimals with a dot, as documented.

**Comment by Chris75forumname** [comment]
This might be straight forward from an internal data point of view. From the user point of view, however, it is confusing and looks like a bug, which means for me, I need to fix it up.
