### ISSUE TITLE
struct type page - prefix for namespace missing

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#641]
Hi, struct type page is in need of a prefix option (just like struct type url and others) to be able to define a default namespace to which the page link points.

**Comment by splitbrain** [comment]
page type always stores full page names. There is support for namespace and postfix in the auto-complete configuration. Implementing a real prefix, where only the entered part is saved, but prefix is then added when rendering (as it is handled in other fields) makes things really difficult when comparing/looking up data.
