### ISSUE TITLE
not compatible with 2023-04-04a Jack Jackrum.

### ISSUE THREAD

**Issue by impactfactory** [cosmocode/dokuwiki-plugin-struct#651]
Confkict with SQLite, doesnt find Plugin, see various reports of upgrade issues: 

https://forum.dokuwiki.org/d/21208-updating-struct-and-sqlite-broke-my-wiki-again

I downgraded to 2023-04-04 "Jack Jackrum" and the old plugin versions and it works again.

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by splitbrain** [comment]
no logs provided

**Comment by impactfactory** [comment]
Well did you see how many people have the same problem? And they found no solutions.

I probably deleted the logs when I rolled everything back. Sorry, Im not a professional developer and it would be good, if we could use struct also in current dokuwiki versions. perhaps you just try to do the same?
