### ISSUE TITLE
Inconsistent behaviour of checkbox field contents when checking/unchecking (breaks filters)

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#658]
Hi,

## Summary

somewhere between version 2023-04-18 and 2023-07-27 of the struct plugin, the behaviour regarding the field contents, when checking and unchecking checkbox fields became inconsistent

- while previously the value for unchecked fields was some "empty" value, it is now NUL
- the content depends on the content (or probably better:  the "last checking action") of other(!) checkbox fields in the same schema when multiple checkbox fields are present

A side effect of this behaviour is, that so far working filters for single-value checkbox fields break.

#### Schema
```
{
    "structversion": "2023-07-27",
    "schema": "s1",
    "id": 44,
    "user": "admin",
    "config": {
        "allowed editors": "",
        "internal": false,
        "label": {
            "en": ""
        }
    },
    "columns": [
        {
            "colref": 1,
            "ismulti": false,
            "isenabled": true,
            "sort": 10,
            "label": "name",
            "class": "Text",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "prefix": "",
                "postfix": "",
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
        },
        {
            "colref": 2,
            "ismulti": false,
            "isenabled": true,
            "sort": 20,
            "label": "f1",
            "class": "Checkbox",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "values": "one",
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
        }
    ]
}
```
#### Default Entry (f1 unchecked)

Entry on page:
<img width="701" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/0bda405f-0c4b-4968-ac00-99631059cc68">

Entry as shown in SQLite interface:
<img width="465" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/8f9a8258-f0fd-4921-96ab-88477c229201">

#### After checking f1

Entry on page:
<img width="700" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/8e5431fd-280d-417e-881a-289e06912e13">

Entry as shown in SQLite interface:
<img width="473" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/c3253c34-3956-478f-be1d-2b54aa530ce4">

#### After unchecking f1 again

Entry on page:
<img width="705" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/d7df16b7-22d3-4ce4-a310-746708c334c4">

Entry as shown in SQLite interface:
<img width="461" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/508d0989-c567-47aa-b1b6-6b9be3079394">

**This new(!) behaviour breaks aggregation filters like**

```
---- struct list ----
schema: s1
cols:   %title%
filter: f1 != one
----
```

**which used to work flawlessly until version 2023-04-18**

#### Schema
```
{
    "structversion": "2023-07-27",
    "schema": "s2",
    "id": 47,
    "user": "admin",
    "config": {
        "allowed editors": "",
        "internal": false,
        "label": {
            "en": ""
        }
    },
    "columns": [
        {
            "colref": 1,
            "ismulti": false,
            "isenabled": true,
            "sort": 10,
            "label": "name",
            "class": "Text",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "prefix": "",
                "postfix": "",
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
        },
        {
            "colref": 2,
            "ismulti": false,
            "isenabled": true,
            "sort": 20,
            "label": "f1",
            "class": "Checkbox",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "values": "one",
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
        },
        {
            "colref": 3,
            "ismulti": false,
            "isenabled": true,
            "sort": 30,
            "label": "f2",
            "class": "Checkbox",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "values": "two",
                "label": {
                    "en": ""
                },
                "hint": {
                    "en": ""
                }
            }
        }
    ]
}
```

#### Default Entry

Entry on page:
<img width="703" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/f8e06ce5-c560-40ca-a2ec-5f68d6354427">

Entry as shown in SQLite interface:
<img width="469" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/bd2b50ff-a33b-42bc-8dec-c349fbc75dfd">

#### Now check first field (f1)

Entry on page:
<img width="707" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/3b78c747-0d86-49d6-bd92-336c0a4b78f8">

Entry as shown in SQLite interface:
<img width="470" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/0592afe4-1268-4562-8f0f-b046725cd784">

#### Uncheck f1 again

Entry on page:
<img width="697" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/c3c97490-49bc-4b0c-b918-c56be8096bd2">

Entry as shown in SQLite interface:
<img width="470" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/9b0f78c2-08ef-4caf-8b49-b3b376fdabbe">

**_So after changing the value of f1, the value of f2 has changed, too_**

#### Check and uncheck f2 (in two steps with a "save" in-between)

Entry on page:
<img width="695" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/a9dbec7b-2cd9-43b6-965b-116ce751a8fc">

Entry as shown in SQLite interface:
<img width="470" alt="image" src="https://github.com/cosmocode/dokuwiki-plugin-struct/assets/279232/1c43fbed-8dfe-4980-8b1d-90407c1ee318">

## Preliminary Thesis

My thesis, based on these and some other checking/unchecking experiments is, that on unchecking a checkbox field
  - this field becomes NUL
  - all other checkbox fields (even if they have **not** been edited) become "empty"

That doesn't feel right

**Comment by fthommen** [comment]
See also the related discussion [in the DokuWiki User Forum](https://forum.dokuwiki.org/d/21420-struct-checkbox-field-becomes-nul-when-unchecked-filter-fails)

**Comment by splitbrain** [comment]
The main issue should be fixed, but I can't really reproduce the second one. Or maybe I misunderstood it and it's fixed anyway? Can you please test and report back?

PS: checkbox values need to be saved again.

**Comment by fthommen** [comment]
> The main issue should be fixed, but I can't really reproduce the second one. Or maybe I misunderstood it and it's fixed anyway? Can you please test and report back?

The fix seems to have fixed both issues. I cannot reproduce the inconsistent behaviour any more. Thx
