### ISSUE TITLE
Enhancement of user-type

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#66]
It would be good to allow "non-existing users" too. Right now, you cannot save values that are non-existing users. Autocompletion on existing wiki-users would be great too.

Use Case: If we document a meeting with participants, it would be great to add users from the wiki (with link to user-profile) AND add other participants that are no wiki users too. Maybe it is enough to do not handle the check for exisiting user as an error but as a warinig. "Are you sure you want to add 'input-name'? This user does not exisit in this wiki."

**Comment by splitbrain** [comment]
Well, the idea of the user field is to link the user name to a user name (or email depending on the showuseras option). Adding people that are not users to such a field makes no sense because where would you link that?

**Comment by stvoigt** [comment]
I see your point and you are right, that was the original idea of the user type :) 
But in the above mentioned use case you do not only have users but also other people. In case that people are not users, just leave it as plain text. See https://wiki.sprintdoc.de/internes:besprechungen:start, we changed in struct-definition from "text type" to "user type" afterwards and got some names left, that are not users of the wiki. They are not linked and that is okay, at least for me :)

**Comment by splitbrain** [comment]
ist jetzt konfigurierbar
