### ISSUE TITLE
Data does not replaced in text

### ISSUE THREAD

**Issue by AP2020C** [cosmocode/dokuwiki-plugin-struct#664]
I added Struct to my DokuWiki on a stick and created a schema and associated it with a page (category).
I read that it is possible to insert the data entered in the schema into the page, e.g. with @@schemaName.fieldName@@ but it is not replaced.
Having verified that the names are spelled correctly, I read that I need to enable a place holder entry in the plugin settings, which however I cannot find.
Where can I find the struct plugin settings?
What do I need to do to see the data in the text?

**Comment by AP2020C** [comment]
After careful research, {{$table.field}} works, but only in the text, not in the titles.
A fix is needed.

**Comment by splitbrain** [comment]
As has pointed out to you before, this is a limitation in DokuWiki and won't be "fixed".
