### ISSUE TITLE
[Is it a bug?] filter action link with comparator "is equal" "=" doesn't work, when "~" does, suprisingly

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#667]
Is this a bug? filter action link with comparator "is equal" "=" doesn't work, when "~" does, suprisingly 

Tested with Jackrum, current versions of sqlite and struct, struct type decimal:

    [[namespace:page?flt[schema.x=]=1|When x is 1]]   // doesn't work, when it should!
    [[namespace:page?flt[schema.x~]=1|When x is 1]]   // works, suprisingly!

**Comment by annda** [comment]
This is how (DokuWiki) links work and it is not a bug in struct. `=` is a reserved character in URLs used to split tokens, and `~` is not. So in the first example you produce a non-interpretable URL parameter of `[schema.x`.

**Comment by splitbrain** [comment]
Ah, right. Good catch @annda. So it should work to url encode the `=` as `%3D`:

```
[[namespace:page?flt[schema.x%3D]=1|When x is 1]]
```

@Chris75forumname maybe you could verify that?

**Comment by Chris75forumname** [comment]
Yes, I can verify that!
