### ISSUE TITLE
[Feature request] - aggregation option "target page": comma-separated list of pages would be useful for table aggregations

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#668]
The aggregation option "target page" is currently only available for filter and cloud aggregations. It accepts: "The page to which filter links should point to. If not specified, the current page is used." 
https://www.dokuwiki.org/plugin:struct:aggregation

This option would be useful in table aggregations to control links in table headers, more than just for sorting. It would be great, if the option accepted a comma-separated list of page IDs as links and a blank space for none, like:
`target     :     , , start, ns:my_page, , ns:other_page`
while, when blank, leaving those headers as-is, for sorting.

Even more, it could also support to skip sorting links that make no sense, like: 
`target     :     , , start, ns:my_page, @none@, ns:other_page`

So, some header links are left as is, for sorting, others point to pages and even others are removed.

**Comment by splitbrain** [comment]
useful how? I don't get what this would achieve? A sort link that sorts a table on a completely different page?

**Comment by Chris75forumname** [comment]
> useful how? I don't get what this would achieve? A sort link that sorts a table on a completely different page?

No, just as a internal link to a page covering the subject of the header, instead of sorting. I think of a table with steps of a process, where the columns are swimlanes and the headers refer to departments. So, the link could point to a page, where contact information is provided.

**Comment by splitbrain** [comment]
I see. I don't think that fits the scope of this plugin. You can use the rest of the wiki to explain your departments.
