### ISSUE TITLE
rownumbers : 1 should work in "table global serial", according to documentation  (does not work in serial)

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#669]
The aggregation option `rownumbers : 1` should work in `table` `global` `serial`, according to documentation. 
It works in `---- struct table ----`, but doesn't work in `---- struct serial ----` (`global` not tested)

**Comment by Chris75forumname** [comment]
I found the culprit: https://codesearch.dokuwiki.org/xref/plugin/struct/syntax/global.php#47
So I guess, I can change the documentation now?

**Comment by splitbrain** [comment]
yes, please update the docs

**Comment by Chris75forumname** [comment]
Done. 😃
