### ISSUE TITLE
Enhancement of page type

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#67]
Right now the autocompletion checks for every existing page, AFAIK. It would be better IMHO to give the config-option (prefix) to limit the name space in which the pages are stored. Wildcard would be helpful too. 

Use Case: If we have a namespace where all project pages/namespace are located we could realize a struct with "project" linking to pages in the project namespaces only. The user would not get the meeting pages or other stuff as a suggestion. As far as I remember we had this in the data-plugin this way.
(Maybe it also makes sense to add a suffix too?)

**Comment by splitbrain** [comment]
implemented. see documentation
