### ISSUE TITLE
Table Aggregation pagination - pagination unexpectedly affects the multiple tables simultaneously

### ISSUE THREAD

**Issue by wataradio** [cosmocode/dokuwiki-plugin-struct#671]
When multiple aggregation tables exist on a page, pagination(`max` option) unexpectedly affects the multiple tables simultaneously.

For example, if you have two aggregation tables on a page like as follows;

```
---- struct table ----
schema: diary
col: date, description, tag
max:10
----

---- struct table ----
schema: vital
col: date, body_tempature, blood_pressure, pulse, weight
max:10
----

```
and click "Next page" on the diary table, then, unexpectedly, the vital table also navigates to the next page simultaneously.

Dokuwiki: 2023-04-04a "Jack Jackrum"
PHP: 7.4

**Comment by wataradio** [comment]
I found `dynfilters` also affected multi tables if they were on the same page.

**Comment by splitbrain** [comment]
all dynamic filters including the pagination filters apply to all aggregations on the page.
