### ISSUE TITLE
Value aggregation: div.structaggregationvalue not being displayed <inline>

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#674]
The documentation says: "Struct Plugin: Value Output ... This is useful to reference a single value inline."
But, value aggregation: div.structaggregationvalue is missing CSS [display: inline-block;]. Thus, it breaks the text structure.
Tested with Jackrum, SprintDoc Template, latest plugin versions.

**Comment by Chris75forumname** [comment]
Solution:
https://forum.dokuwiki.org/d/21689-how-to-use-struct-aggregation-values-inline/4

**Comment by cjohnsonuk** [comment]
Even with the additional CSS the rendered HTML includes a closing paragraph tag immediately before the inserted aggregation value.  This also results in any text following the aggregation value not being inside any paragraph tags.

This markup
`Only {{$doc_data.owner}} can grant other employees access to the any of the above-mentioned records.`
translates into this html

```
<p>Only </p>
<div class="structaggregation structaggregationvalue" style=" display: inline-block;">
  <span class="struct_user">John Doe</span>
</div> 
can grant other employees access to the any of the above-mentioned records.
<p></p>
```
giving me this output

```
Only
John Doe can grant other employees access to the any of the above-mentioned records.
```

The output html would be better if the closing `<\p>` tag was moved to the end of the text block (moved from after `Only` to after `records`: 
```
<p>Only 
<div class="structaggregation structaggregationvalue" style=" display: inline-block;">
  <span class="struct_user">John Doe</span>
</div> 
can grant other employees access to the any of the above-mentioned records.</p>
<p></p>
```
