### ISSUE TITLE
The scheme is always assigned to sub-namespaces as well

### ISSUE THREAD

**Issue by AP2020C** [cosmocode/dokuwiki-plugin-struct#676]
When I try to assign a schema to a namespace, I notice that it is always assigned to both the namespace and the subnamespaces, regardless of whether I use namespace:* or namespace:**.
Is there a reason for this? From the description
> Namespaces excluding subnamespaces are assigned as namespace:*.
> Namespaces including subnamespaces are assigned as namespace:**.

seems to be a bug.

**Comment by annda** [comment]
I can't reproduce the error. Can you please post your **exact** assignment rules, not just examples? And affected page ids?

**Comment by splitbrain** [comment]
no additional info provided
