### ISSUE TITLE
[bug] Allow deleting all values from a multi-value field (type: media) in inline editor

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#677]
Hi, I cannot delete last remaining value from a multi-value field in inline editor (field type: media).
I can overwrite/delete 3rd entry, 2nd entry and so on, but when I try to overwrite 1st entry with empty input, the dialog quietly dies and leaves the entry in place (without error message). (tested with Jackrum and recent versions of plugins)

**Comment by Chris75forumname** [comment]
I found the bug! Look here:
https://codesearch.dokuwiki.org/xref/plugin/struct/meta/ValueValidator.php#33
I removed the `&` from `&$rawvalue` in the function header of `validateValue()` function. And voila, the values can be deleted now, that is, overwritten with nothing ''. And validation remains functioning with this fix.
Cheers!

**Comment by annda** [comment]
Fixed in #684
