### ISSUE TITLE
Autocomplete fails for usernames that are only digits

### ISSUE THREAD

**Issue by cmacmackin** [cosmocode/dokuwiki-plugin-struct#689]
I have a wiki in which most usernames are numeric (they are membership numbers of an existing organisation). When I try to use the autocomplete for `User`-type data, it returns logins that start at 0. I've created an example wiki with the following users
![Screenshot from 2023-11-18 20-31-35](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/8145213/7e5cb995-6245-423b-a0aa-5bf5477dc629)

When I try to use auto-complete, this is what happens
![Screenshot from 2023-11-18 20-32-48](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/8145213/87d42e88-34b8-431d-a4da-f52771a46afc)

I've done a bit of debugging and worked out that the reason is [the user of array_merge](https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/types/User.php#L86). The numeric usernames are returned as integer data in the associative array produced by `$auth->retrieveUsers()`. According to PHP [documentation for array_merge](https://www.php.net/manual/en/function.array-merge), "Values in the input arrays with numeric keys will be renumbered with incrementing keys starting from zero in the result array."

I'm not sure whether we should look to change this in the main Dokuwiki code so that `$auth->retrieveUsers()` returns numeric username keys as strings or whether it would be better just to do the conversion in this plugin. I'm happy to submit a merge request for either.

**Comment by splitbrain** [comment]
> change this in the main Dokuwiki code so that $auth->retrieveUsers() returns numeric username keys as strings

I wish we could do this. This is unfortunately one of those things in PHP that are super weird and broken. PHP will consider this a numeric key, no matter what: `$foo[(string) "1234"] = 'what?';` The only work around would be prefixing all keys with a string - hardly backward compatible.

So the fix needs to be applied in struct, when consuming the returned array.

**Comment by splitbrain** [comment]
see da8d86ad959e9e54cfe300f1b65923189ae00dee where I encountered a similar problem (the fix there is probably not applicable here)
