### ISSUE TITLE
Feature request: versioning record changes

### ISSUE THREAD

**Issue by Harliff** [cosmocode/dokuwiki-plugin-struct#698]
The only thing that prevents the active use of a master database based on the "struct" is the lack of versioning of record changes. 

How about adding this feature in the next major version?

I would recommend to implement: 
- the ability to turn on/off the general record keeping 
- the ability to turn on/off the history in the context of the scheme column 
- the ability to limit the depth of history globally 
- the ability to limit the depth of the history in the context of the schema column 
- the ability to shorten (truncate) the record history for each column of the schema

**Comment by splitbrain** [comment]
Struct page data is already versioned. Versioning for global and serial data is not planned.
