### ISSUE TITLE
implement type page

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#7]
We have this already, but it needs to have some configuration options for at least prefix and postfix

This basically covers the nspage functionality, so we won't need that type anymore.

**Comment by stvoigt** [comment]
It would be great to have a config option on that page-type to either display the page-name or the title/first headline of the page. Currently this can only be done in the main admin space for all links to display page-name or title, AFAIK.

**Comment by splitbrain** [comment]
This is related to #8. Adding this config option would be trivial but it would only affect how the result is displayed. People would reasonably expect to be able to filter and sort by title as well. I'm leaving this closed as it is better covered in #8

**Comment by stvoigt** [comment]
I like the autocompletion functionality very much for pages. Would be great to have this here too :-)
(But I am not sure, if this was from the page-type in data plugin or a functionality from bureaucracy plugin)

**Comment by splitbrain** [comment]
Autocompletion makes sense. I just added it for the new user type. So the basic functionality is there already.

- [ ] add autocompletion

**Comment by stvoigt** [comment]
As you mentioned the expectations of users regarding sorting/filtering/autocompletion on page titles. Yes, that would be great too :) I know from a discussion a year ago that this is tricky. Would it be possible to add kind of hidden-type that contains metadata of a page (author, last edit, title) that is automatically updated by saving a page? Thus it would be possible to make queries on page properties. I could open a new issue, if you want...

**Comment by stvoigt** [comment]
Bug: When you have page and user in one struct and user is multi-value, the content of the page-field is copied automatically with the numbers of users. E.g. if you have a three users added, you get the page also three times (automatically), changing users to four will result in four times page content. See: https://wizmo.projekt-wiki.sprintdoc.de/meetings:sprintdoc_schulung
