### ISSUE TITLE
[Syntax Error] Using struct-fields in bureaucracy linking to pages

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#700]
Yesterday my bureaucracy form worked well. Today I updated the struct plugin. After plugin update I got an error when using the form:

![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/2620833/6088ef2a-5d47-4807-8dfa-024958d1e7d6)

The form uses: struct_field "events.otherpartners" !

Definition in struct editor:
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/2620833/95677376-df2f-440b-96df-4d7108705711)

The selection of the page (autocompletion) works, but after submitting the form, I got the error and "Array" in my form field.

**Comment by annda** [comment]
The error seems to occur only when 'usetitles' is set to true and the page field accepts multiple values. We are working on a fix.

**Comment by stvoigt** [comment]
I get the same error, even if if both options are disabled... 
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/2620833/4b6d37dc-fa70-4637-a20f-7d7d189a891b)

**Comment by stvoigt** [comment]
Ich bekomme auch bei anderen bureaucracy Formularen mit struct-Feldern einen Syntax-Error. Bspw. wenn ich ein DropDown-Feld integriere. Nehme ich dieses raus, funktioniert es.
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/2620833/f0c34c80-54a8-4a8e-8c29-d0acfbaf9be8)

**Comment by Juergen-aus-Zuendorf** [comment]
Same problem

**Comment by annda** [comment]
@Juergen-aus-Zuendorf Thanks for confirming. I cannot reproduce the syntax error message no matter what I do. Which errors do you see?

- Syntax error? With which fields?
- "Array" with page field and settings `multi` and `usetitles`?
- "Array" with page field and the above settings disabled?

**Comment by Juergen-aus-Zuendorf** [comment]
This code alone already generates an error:

```
fieldset "Grunddaten"
struct_field "cms_akat_daten.cms-akattyp" "=["""",2]"

fieldset "Daten anlegen"
action template _ test
submit "Katalogblatt für Pinolenzubehör anlegen"

```
The field "cms-akattyp" contains a lookup value. The array only allows single values. The parameter "usetitles" is enabled in the wiki.

**Comment by annda** [comment]
@Juergen-aus-Zuendorf What is the exact error? When exactly does it appear? (When opening the page with the form, when submitting incomplete data, when submitting complete data?) Does the page get created?

**Comment by Juergen-aus-Zuendorf** [comment]
The message comes up after filling the value and subsequently clicking the submit button. The error message only says "Syntax error", and nothing else. The page isn't created.

**Comment by vic-t** [comment]
Hi @annda , I was affected by the same issue and @Juergen-aus-Zuendorf pointed me to this issue report. I just patched the 3 files in the struct plugin manually with your changes and it all works again. Thanks.

**Comment by annda** [comment]
@vic-t Thank you for your feedback. The changes have been merged and are available after you reinstall the plugin in extension manager (an update will become visible later in the day).
@stvoigt @Juergen-aus-Zuendorf Can you please confirm that the latest version fixes all the errors?

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you, my first test was successful; no error message, page is created

**Comment by stvoigt** [comment]
Thank you! Works well!
