### ISSUE TITLE
Control Clouds - not working with the 2024-04-09 version

### ISSUE THREAD

**Issue by LMS235** [cosmocode/dokuwiki-plugin-struct#713]
### Issue Description

Since the current version 2024-04-09 (at least that's where I noticed it), the cloud display (https://www.dokuwiki.org/plugin:struct:cloud) no longer works.

here is our code

```
---- struct cloud ----
schema: schema
field: field
page
target: namespace:site
limit: 20
summarize: yes
----
```

The page simply remains empty. Everything else (table view etc.) works without problems, it only affects the cloud view.

2024-02-06a
Apache with PHP 8.2.18 fpm-fcgi
struct 2024-04-09

**Comment by bvdbos** [comment]
The generated page:
`
                    
<h1 class="sectionedit1" id="boeken_tags">Boeken Tags</h1>
<div class="level1">
<div class="structaggregation structaggregationcloud"><ul>
</ul>
</div>


</div>
                    `

**Comment by bvdbos** [comment]
The generated page:
```javascript
<!-- wikipage start -->                   
<h1 class="sectionedit1" id="boeken_tags">Boeken Tags</h1>
<div class="level1">
<div class="structaggregation structaggregationcloud"><ul>
</ul>
</div>
</div>
                    <!-- wikipage stop -->
```

**Comment by StarArmy** [comment]
Thanks for making this bug report for this issue I reported on the Dokuwiki forum in March. I realize that this is a free open source software but I didn't expect that this issue would be unresolved for so long.
