### ISSUE TITLE
SQLSTATE[HY000]: General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by zkhuber** [cosmocode/dokuwiki-plugin-struct#719]
### Issue Description

I have problem with struct database. Probably I had similar problem last year when number of struct database was change. After changing it to number 19 using UPDATE opts SET val=19 WHERE opt='dbversion' helped in problem. Now struct database number was change to 20. I tried change it to 19 using above formula but after this I get error: PDOException: SQLSTATE[HY000]: General error: 1 index idx_data_ksiazka_latest already exists. It was necessary uninstall struct plugin to make webpage functional.

Error before changing struct database number
2024-06-23 22:00:12	.../lib/plugins/sqlite/SQLiteDB.php(161)	PDOException: SQLSTATE[HY000]: General error: 11 database disk image is malformed
  #0 .../lib/plugins/sqlite/SQLiteDB.php(161): PDOStatement->execute()
  #1 .../lib/plugins/sqlite/SQLiteDB.php(228): dokuwiki\plugin\sqlite\SQLiteDB->query()
  #2 .../lib/plugins/struct/meta/PageMeta.php(42): dokuwiki\plugin\sqlite\SQLiteDB->queryRecord()
  #3 .../lib/plugins/struct/action/title.php(48): dokuwiki\plugin\struct\meta\PageMeta->getPageData()
  #4 .../inc/Extension/EventHandler.php(80): action_plugin_struct_title->handleMeta()
  #5 .../inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
  #6 .../inc/parserutils.php(540): dokuwiki\Extension\Event->advise_after()
  #7 .../inc/parserutils.php(299): p_render_metadata()
  #8 .../inc/Cache/CacheRenderer.php(79): p_get_metadata()
  #9 .../inc/Cache/Cache.php(79): dokuwiki\Cache\CacheRenderer->addDependencies()
  #10 .../inc/parserutils.php(152): dokuwiki\Cache\Cache->useCache()
  #11 .../inc/parserutils.php(97): p_cached_output()
  #12 .../inc/template.php(1658): p_wiki_xhtml()
  #13 .../lib/tpl/bootstrap3/Template.php(1440): tpl_include_page()
  #14 .../lib/tpl/bootstrap3/tpl/navbar.php(65): dokuwiki\template\bootstrap3\Template->getNavbar()
  #15 .../lib/tpl/bootstrap3/main.php(51): require_once('...')
  #16 .../inc/actions.php(30): include('...')
  #17 .../doku.php(131): act_dispatch()
  #18 {main}

Error after changing struct database number to 19:
2024-06-27 07:39:26	.../lib/plugins/sqlite/SQLiteDB.php(151)	PDOException: SQLSTATE[HY000]: General error: 1 index idx_data_ksiazka_latest already exists
  #0 .../lib/plugins/struct/action/migration.php(363): dokuwiki\plugin\sqlite\SQLiteDB->query()
  #1 .../lib/plugins/struct/action/migration.php(44): action_plugin_struct_migration->migration20()
  #2 .../inc/Extension/EventHandler.php(80): action_plugin_struct_migration->handleMigrations()
  #3 .../inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
  #4 .../lib/plugins/sqlite/SQLiteDB.php(441): dokuwiki\Extension\Event->advise_before()
  #5 .../lib/plugins/sqlite/SQLiteDB.php(83): dokuwiki\plugin\sqlite\SQLiteDB->applyMigrations()
  #6 .../lib/plugins/struct/helper/db.php(27): dokuwiki\plugin\sqlite\SQLiteDB->__construct()
  #7 .../lib/plugins/struct/helper/db.php(53): helper_plugin_struct_db->init()
  #8 .../lib/plugins/struct/meta/PageMeta.php(22): helper_plugin_struct_db->getDB()
  #9 .../lib/plugins/struct/action/title.php(45): dokuwiki\plugin\struct\meta\PageMeta->__construct()
  #10 .../inc/Extension/EventHandler.php(80): action_plugin_struct_title->handleMeta()
  #11 .../inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
  #12 .../inc/parserutils.php(540): dokuwiki\Extension\Event->advise_after()
  #13 .../inc/parserutils.php(299): p_render_metadata()
  #14 .../inc/common.php(262): p_get_metadata()
  #15 .../doku.php(101): pageinfo()
  #16 {main}

Any help with this problem.
Regards 
Huber

**Comment by splitbrain** [comment]
If you don't know what you're doing do not fuck with the database version!

> index idx_data_ksiazka_latest already exists

This is because you changed the database versions and now the sqlite plugin tries to apply the migrations again. Restore your backup.

> General error: 11 database disk image is malformed

This seems to indicate that your database got corrupted.

Opening the database in sqlite3 and issuing a `PRAGMA integrity_check;` might reveal more info.

The LocusMap project has some good hints on how to attempt recovering a corrupted database: https://docs.locusmap.app/doku.php?id=manual:advanced:map_tools:corrupted_sqlite#general_solution

**Comment by zkhuber** [comment]
Thanks for your respond.And sorry to upset you. Was no my intention. When my site was not functional (showed only error) my first action was to change database number because last year this was a solution. So now a solution for the problem is another one. I will try check around.But in this moment I can`t use struct plugin.
But still in my backup the number of database is still 19:INSERT INTO 'opts' VALUES ('dbversion','19');INSERT INTO 'types' VALUES ('1','Text','0','Title','{    "visibility": {        "inpage": true,        "ineditor": true
I hope this will be not a problem because I change it back to 20.
 I'm sorry I don't understand much of this, but I'm just an average internet user. Not a guru who can write such wonderful programs. For which I would like to express my sincere thanks.

Regards
Huber
    W czwartek, 27 czerwca 2024 10:40:54 CEST, Andreas Gohr ***@***.***> napisał(-a):  
 
 


If you don't know what you're doing do not fuck with the database version!


index idx_data_ksiazka_latest already exists


This is because you changed the database versions and now the sqlite plugin tries to apply the migrations again. Restore your backup.


General error: 11 database disk image is malformed


This seems to indicate that your database got corrupted.

Opening the database in sqlite3 and issuing a PRAGMA integrity_check; might reveal more info.

The LocusMap project has some good hints on how to attempt recovering a corrupted database: https://docs.locusmap.app/doku.php?id=manual:advanced:map_tools:corrupted_sqlite#general_solution
