### ISSUE TITLE
filter placeholders 

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#75]
Allow dynamic aggregation filters via placeholders.

We need placeholders for:

- [x] current page ID
- [x] current page name (no namespace)
- [x] current namespace
- [x] current user :point_up: 
- [x] current date (maybe even strftime placeholders?) :point_up:
- [x] a struct value of the current page

- [x] :point_up: dynamic placeholders that need special handling in caching strategy over what we have already

**Comment by splitbrain** [comment]
@detman @stvoigt What would be a good syntax for the placeholders? We need something that is easily recognizable as a placeholder and will not clash with (most) other normal filters.

**Comment by stvoigt** [comment]
Maybe it is good to be consistant with template placeholders? @@placeholdername@@ or ##placeholdername##?

**Comment by splitbrain** [comment]
@stvoigt wouldn't that make it really hard to use the syntax in breaucracy templates?

**Comment by stvoigt** [comment]
You are right, that would mean a @@@@placeholdername@@@@ in template -1:

**Comment by splitbrain** [comment]
I currently lean towards ``$ID$``, ``$USER$``, ``$STRUCT.column$``

**Comment by stvoigt** [comment]
:+1:

**Comment by detman** [comment]
$STRUCT.column$ -> what about the scheme name? 
I suggest `$STRUCT.scheme.column$`

**Comment by splitbrain** [comment]
@detman the column name is resolved through the configured schemas in the aggregation. The syntax you suggest would be valid, but the schema name can be omitted if the column name is unique. You could also use a configure alias instead of the full schema name.

**Comment by splitbrain** [comment]
implemented now.

**Comment by splitbrain** [comment]
docs here: https://www.dokuwiki.org/plugin:struct:filters
