### ISSUE TITLE
Bug: struct values are not deleted on page delete

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#77]
Aggregations are still shown for no existing pages, at least in the wizmo wiki.

**Comment by splitbrain** [comment]
@detman reproduced the problem when moving a page with the move plugin. Related to #72

**Comment by stvoigt** [comment]
You can see this still in ifak/products:start => Testprodukt_1 was deleted but still appears in the aggregation.

**Comment by splitbrain** [comment]
Okay. The struct values were correctly cleared (all columns empty) but since there is no additional filter, the page still matches. I guess we need an additional page_exists check.
