### ISSUE TITLE
implement type title

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#8]
This is difficult, because we currently do not have the titles in the database. The data plugin used to have a list of all pages and their titles. I think we will need something like that again.

**Comment by iainhallam** [comment]
This would make the data from the plugin much more usable for my users, particularly on aggregation pages, where we could have %pagetitle% instead of just ID.

**Comment by splitbrain** [comment]
usetitles is now available for page types, but a %pagetitle% placeholder is not available, yet.

**Comment by micgro42** [comment]
We also need either need $TITLE$ placeholder or need to make sure $PAGE$ and $ID$ still work for titles.

**Comment by micgro42** [comment]
Also: What does the ``$STRUCT.colname$`` placeholder return for such a title column? The title or the pageid?

**Comment by splitbrain** [comment]
Autocompletion currently behaves like quicksearch works. Showing the title with the namespace in parentheses.

``$STRUCT.colname$`` is indeed broken, as it would contain the JSON structure. We have to improve this.

**Comment by splitbrain** [comment]
Broken and missing features are now listed as their own tickets: #131 #130 #129 #132
