### ISSUE TITLE
Bug: aggregation do not work

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#81]
Error: 
HY000 1 no such function: PAGEEXISTS:

See WIZMO/ifak wikis... Every page containing an aggregation gives this error...

**Comment by splitbrain** [comment]
the sqlite plugin needs to be updated @micgro42 can you look at that? I think it can be updated through the extension manager in the farmer

**Comment by micgro42** [comment]
Update has been done, but there are still errors. I'm looking into it further.

**Comment by micgro42** [comment]
Ok, fixed. I accidentally updated the struct - plugin as well. But there should be no harm in that, right?

**Comment by splitbrain** [comment]
should be fine
