### ISSUE TITLE
Bug: editing imported struct schema

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#82]
To test the bureaucracy features I have copied the ifak forms/templates/aggregations to the foo-wiki. I also imported the struct schemas. I had to edit struct schema regarding type pages due to different namespaces in the foo wiki. After saving, the entry was lost. You can see this in the  ifakproject, ifakfaq and ifakmeeting. The page types are all lost. (see that sorting starts with 20, not with 10)
[I have found the bug because autocompletion from the project page to a product page did not work, so the product-struct-type was on the project-page... I realized that I had to change the namespace in struct editor. After saving the changes, the product-struct-type on the project page was lost...)

Another thing is, that the labels do not work. just edit ifak:projects:ci4level:start, you will only see the names, not the labels. I am not sure if this is also because of importing the schema...

**Comment by stvoigt** [comment]
Maybe there are different versions of the struct plugin installed (I thought that foo belongs to the farm)? I can see the schema import/export dialog below the struct schema editor in foo but not in ifak wiki...

**Comment by stvoigt** [comment]
It seems that the Labels were not imported at all.

**Comment by splitbrain** [comment]
I just imported the file you sent me and labels were imported just fine!?

**Comment by stvoigt** [comment]
Now I've got it! Foo is an English wiki, ifak a German one... So I imported German labeled struct schema into English wiki. Thus I cannot see the German labels, because Foo has only one Language (English). What would happen if I turn Foo into German via config? Are the German labels within the struct schema or are they lost? (I just checked this out: They are lost...)

**Comment by splitbrain** [comment]
Yeah Schemas discard unknown config options. That includes unknown languages. Closing this.
