### ISSUE TITLE
Bug: Bureaucracy/struct handover of namespace does not work correctly

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#85]
See wizmo>projekt:smartvet:components:magazin and click on "Neues Element anlegen".
I handover the namespace of the component and use this as the target namespace. It is shown correctly in the form with "projekt:smartvet:components:magazin", but the page is created in namespace "projekt_smartvet_components_magazin_test" so the ":" becomes an "_".

**Comment by splitbrain** [comment]
I believe this is not a problem with struct. AFAIR bureaucracy will replace colons in all the fields that are used to create the new pagename via the @ syntax to avoid that people create their own sub namespaces.
Try to recreate this without struct fields and it will probably behave exactly the same.
