### ISSUE TITLE
Enhancement: struct-media-type in bureaucracy

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#86]
If I am using an media type in struct and thus in bureaucracy, the image that I will upload will be uploaded to the namespace the form is located in. It would be useful to transfer the media to the destination of the created page afterwards.
(see wizmo>template:element_form)

**Comment by splitbrain** [comment]
Struct does not do any uploading. The media type references existing media files. When you use the media popup to upload an image you're free to do so wherever you want.
It makes no sense for struct or bureaucracy to move such a media file as it can't possibly know if it was uploaded right now just for this form or if an existing media file was referenced.
