### ISSUE TITLE
Bug: optional struct-media-type in bureaucracy will throw an error message when empty

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#87]
Error when leaving empty: MIME type has to match the allowed set of image/
See: wizmo>template:element_form

**Comment by splitbrain** [comment]
Hmm... there's a deeper underlying problem I overlooked. Handling of multivalue fields is not correct either.

**Comment by splitbrain** [comment]
@stvoigt can you do some experiments if everything works correctly now?

**Comment by stvoigt** [comment]
I can confirm, that optional media-type works...
