### ISSUE TITLE
Bug: struct/bureaucracy template namespace

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#88]
When building a namespace out of struct-elements the ":" will be replaced with "_"
See wizmo>projekt:smartvet:components:magazin => Neues Element anlegen

**Comment by stvoigt** [comment]
this is quite strange. I tried a version without using struct-elements/struct-schema in bureaucracy but got the same behavior as mentioned above. (see See wizmo>projekt:smartvet:components:magazin => "Neues Element ohne struct anlegen")
On the other hand the same thing works if you use the wizmo>template:component_form, here the namespace is also connected with two variables. why does this not work with three?

**Comment by stvoigt** [comment]
tried new component with three namespace-variables (see wizmo>template:component_form2). Works fine. Is it because of the datatype? textboxes and hidden vs. only textboxes?
@splitbrain could you please have a look at this, otherwise I cannot finish the task for wizmos "new element" stuff...

**Comment by splitbrain** [comment]
So, I digged through the bureaucracy code a bit...

- page name parts are accessed through a value called 'pagename' [actiontemplate.php#71](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/blob/master/helper/actiontemplate.php#L71)
- that is actually not a real value, but just adds "escaping" namespace separators [field.php#285](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/blob/master/helper/field.php#L285)
- except for hidden fields [fieldhidden.php#40](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/blob/master/helper/fieldhidden.php#L40)

that doesn't solve anything, yet.. just written down here for better understanding...

**Comment by splitbrain** [comment]
Ahhh Your Syntax is wrong!

It's ```action template [template] [destination] [separator]`` You're only giving it two parameters: the template and the separator. The destination is missing. Give it another colon as destination as well.

**Comment by stvoigt** [comment]
so the user was the bug... again. sorry...
