### ISSUE TITLE
Development roadmap and schedule

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#91]
Is there a roadmap of what major features still have to be developed, and any idea of when struct will become production-ready or what releases will be made?

**Comment by splitbrain** [comment]
The plugin is in a state where it is actively used on our internal wiki at CosmoCode as well as in several project wikis in the SprintDoc research project (https://www.sprintdoc.de/). There are currently no immediate plans on further feature development as the plugin currently covers our needs.

According to our planning in the SprintDoc project, we will revisit this plugin for evaluation and minor corrections in about two months (@stvoigt or @detman might know better).

We're open for suggestions and pull requests. You're also welcome to hire us if you need features that are currently missing http://www.cosmocode.de/en/open-source/dokuwiki-plugins/

Current development roadmaps (once available) will be maintained at https://github.com/cosmocode/dokuwiki-plugin-struct/milestones

**Comment by iainhallam** [comment]
Quick question, though; which release will make develonly tag obsolete?

**Comment by splitbrain** [comment]
The upcoming DokuWiki release. This plugin uses features that currently are available in DokuWiki's master branch only

**Comment by iainhallam** [comment]
Thanks for the info.
