### ISSUE TITLE
Support collections as data types

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#93]
The data plugin has the concept of arrays where any field can contain multiple values. In issue #92 I've asked for struct to be able to support nesting of objects, and I gave the example of modelling membership of an organisation, where a Person has a Membership. Actually, people can leave and join again, so I'd like to maintain a list of past Membership objects as part of the Person structured data, which would mean the Person schema supporting an array of structs. In this case it would be an ordered list, but other collection types such as set or dictionary/hash might be useful as well.

**Comment by splitbrain** [comment]
Each field in struct has a ``multi`` property already. When set, the field accepts multiple values of the same type.

**Comment by iainhallam** [comment]
Apologies; didn't spot this in the docs.
