### ISSUE TITLE
Restrict tags to a set vocabulary

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#94]
To prevent users just creating extra tags, is there any way to restrict them to a set list of valid tags, somehow?

**Comment by splitbrain** [comment]
no. and that's not how tags are intended to work. They are free form categorization.

**Comment by iainhallam** [comment]
So how is it best to classify my items in a set vocabulary?

**Comment by splitbrain** [comment]
The Dropdown or Checkbox types come to mind. An alternative would be the implementation of #37

**Comment by iainhallam** [comment]
OK; I might try creating pages for each term in a namespace then use a page field to choose between them. That way I can get links to all pages classified with that term, like the tags, and pre-create the ones I want used. Users will still be able to enter their own page names, but they won't get linked anywhere.
